// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.1
// source: notify.proto

package notify

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	NotifyService_CreateCancellation_FullMethodName  = "/notify.NotifyService/CreateCancellation"
	NotifyService_GetAllCancellations_FullMethodName = "/notify.NotifyService/GetAllCancellations"
	NotifyService_GetCancellationByID_FullMethodName = "/notify.NotifyService/GetCancellationByID"
	NotifyService_UpdateCancellation_FullMethodName  = "/notify.NotifyService/UpdateCancellation"
	NotifyService_DeleteCancellation_FullMethodName  = "/notify.NotifyService/DeleteCancellation"
	NotifyService_CreateSuccess_FullMethodName       = "/notify.NotifyService/CreateSuccess"
	NotifyService_GetAllSuccesses_FullMethodName     = "/notify.NotifyService/GetAllSuccesses"
	NotifyService_GetSuccessByLeadID_FullMethodName  = "/notify.NotifyService/GetSuccessByLeadID"
	NotifyService_UpdateSuccess_FullMethodName       = "/notify.NotifyService/UpdateSuccess"
	NotifyService_DeleteSuccess_FullMethodName       = "/notify.NotifyService/DeleteSuccess"
)

// NotifyServiceClient is the client API for NotifyService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type NotifyServiceClient interface {
	CreateCancellation(ctx context.Context, in *CreateCancellationRequest, opts ...grpc.CallOption) (*CancellationResponse, error)
	GetAllCancellations(ctx context.Context, in *GetByLeadIDRequest, opts ...grpc.CallOption) (*CancellationListResponse, error)
	GetCancellationByID(ctx context.Context, in *GetByMeetingIDRequest, opts ...grpc.CallOption) (*CancellationResponse, error)
	UpdateCancellation(ctx context.Context, in *UpdateCancellationRequest, opts ...grpc.CallOption) (*CancellationResponse, error)
	DeleteCancellation(ctx context.Context, in *DeleteByMeetingIDRequest, opts ...grpc.CallOption) (*DeleteResponse, error)
	CreateSuccess(ctx context.Context, in *CreateSuccessRequest, opts ...grpc.CallOption) (*SuccessResponse, error)
	GetAllSuccesses(ctx context.Context, in *GetByLeadIDRequest, opts ...grpc.CallOption) (*SuccessListResponse, error)
	GetSuccessByLeadID(ctx context.Context, in *GetByLeadIDRequest, opts ...grpc.CallOption) (*SuccessResponse, error)
	UpdateSuccess(ctx context.Context, in *UpdateSuccessRequest, opts ...grpc.CallOption) (*SuccessResponse, error)
	DeleteSuccess(ctx context.Context, in *GetByLeadIDRequest, opts ...grpc.CallOption) (*DeleteResponse, error)
}

type notifyServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewNotifyServiceClient(cc grpc.ClientConnInterface) NotifyServiceClient {
	return &notifyServiceClient{cc}
}

func (c *notifyServiceClient) CreateCancellation(ctx context.Context, in *CreateCancellationRequest, opts ...grpc.CallOption) (*CancellationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CancellationResponse)
	err := c.cc.Invoke(ctx, NotifyService_CreateCancellation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *notifyServiceClient) GetAllCancellations(ctx context.Context, in *GetByLeadIDRequest, opts ...grpc.CallOption) (*CancellationListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CancellationListResponse)
	err := c.cc.Invoke(ctx, NotifyService_GetAllCancellations_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *notifyServiceClient) GetCancellationByID(ctx context.Context, in *GetByMeetingIDRequest, opts ...grpc.CallOption) (*CancellationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CancellationResponse)
	err := c.cc.Invoke(ctx, NotifyService_GetCancellationByID_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *notifyServiceClient) UpdateCancellation(ctx context.Context, in *UpdateCancellationRequest, opts ...grpc.CallOption) (*CancellationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CancellationResponse)
	err := c.cc.Invoke(ctx, NotifyService_UpdateCancellation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *notifyServiceClient) DeleteCancellation(ctx context.Context, in *DeleteByMeetingIDRequest, opts ...grpc.CallOption) (*DeleteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteResponse)
	err := c.cc.Invoke(ctx, NotifyService_DeleteCancellation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *notifyServiceClient) CreateSuccess(ctx context.Context, in *CreateSuccessRequest, opts ...grpc.CallOption) (*SuccessResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SuccessResponse)
	err := c.cc.Invoke(ctx, NotifyService_CreateSuccess_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *notifyServiceClient) GetAllSuccesses(ctx context.Context, in *GetByLeadIDRequest, opts ...grpc.CallOption) (*SuccessListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SuccessListResponse)
	err := c.cc.Invoke(ctx, NotifyService_GetAllSuccesses_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *notifyServiceClient) GetSuccessByLeadID(ctx context.Context, in *GetByLeadIDRequest, opts ...grpc.CallOption) (*SuccessResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SuccessResponse)
	err := c.cc.Invoke(ctx, NotifyService_GetSuccessByLeadID_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *notifyServiceClient) UpdateSuccess(ctx context.Context, in *UpdateSuccessRequest, opts ...grpc.CallOption) (*SuccessResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SuccessResponse)
	err := c.cc.Invoke(ctx, NotifyService_UpdateSuccess_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *notifyServiceClient) DeleteSuccess(ctx context.Context, in *GetByLeadIDRequest, opts ...grpc.CallOption) (*DeleteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteResponse)
	err := c.cc.Invoke(ctx, NotifyService_DeleteSuccess_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NotifyServiceServer is the server API for NotifyService service.
// All implementations must embed UnimplementedNotifyServiceServer
// for forward compatibility.
type NotifyServiceServer interface {
	CreateCancellation(context.Context, *CreateCancellationRequest) (*CancellationResponse, error)
	GetAllCancellations(context.Context, *GetByLeadIDRequest) (*CancellationListResponse, error)
	GetCancellationByID(context.Context, *GetByMeetingIDRequest) (*CancellationResponse, error)
	UpdateCancellation(context.Context, *UpdateCancellationRequest) (*CancellationResponse, error)
	DeleteCancellation(context.Context, *DeleteByMeetingIDRequest) (*DeleteResponse, error)
	CreateSuccess(context.Context, *CreateSuccessRequest) (*SuccessResponse, error)
	GetAllSuccesses(context.Context, *GetByLeadIDRequest) (*SuccessListResponse, error)
	GetSuccessByLeadID(context.Context, *GetByLeadIDRequest) (*SuccessResponse, error)
	UpdateSuccess(context.Context, *UpdateSuccessRequest) (*SuccessResponse, error)
	DeleteSuccess(context.Context, *GetByLeadIDRequest) (*DeleteResponse, error)
	mustEmbedUnimplementedNotifyServiceServer()
}

// UnimplementedNotifyServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedNotifyServiceServer struct{}

func (UnimplementedNotifyServiceServer) CreateCancellation(context.Context, *CreateCancellationRequest) (*CancellationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateCancellation not implemented")
}
func (UnimplementedNotifyServiceServer) GetAllCancellations(context.Context, *GetByLeadIDRequest) (*CancellationListResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAllCancellations not implemented")
}
func (UnimplementedNotifyServiceServer) GetCancellationByID(context.Context, *GetByMeetingIDRequest) (*CancellationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCancellationByID not implemented")
}
func (UnimplementedNotifyServiceServer) UpdateCancellation(context.Context, *UpdateCancellationRequest) (*CancellationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateCancellation not implemented")
}
func (UnimplementedNotifyServiceServer) DeleteCancellation(context.Context, *DeleteByMeetingIDRequest) (*DeleteResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteCancellation not implemented")
}
func (UnimplementedNotifyServiceServer) CreateSuccess(context.Context, *CreateSuccessRequest) (*SuccessResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateSuccess not implemented")
}
func (UnimplementedNotifyServiceServer) GetAllSuccesses(context.Context, *GetByLeadIDRequest) (*SuccessListResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAllSuccesses not implemented")
}
func (UnimplementedNotifyServiceServer) GetSuccessByLeadID(context.Context, *GetByLeadIDRequest) (*SuccessResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSuccessByLeadID not implemented")
}
func (UnimplementedNotifyServiceServer) UpdateSuccess(context.Context, *UpdateSuccessRequest) (*SuccessResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateSuccess not implemented")
}
func (UnimplementedNotifyServiceServer) DeleteSuccess(context.Context, *GetByLeadIDRequest) (*DeleteResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteSuccess not implemented")
}
func (UnimplementedNotifyServiceServer) mustEmbedUnimplementedNotifyServiceServer() {}
func (UnimplementedNotifyServiceServer) testEmbeddedByValue()                       {}

// UnsafeNotifyServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NotifyServiceServer will
// result in compilation errors.
type UnsafeNotifyServiceServer interface {
	mustEmbedUnimplementedNotifyServiceServer()
}

func RegisterNotifyServiceServer(s grpc.ServiceRegistrar, srv NotifyServiceServer) {
	// If the following call panics, it indicates UnimplementedNotifyServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&NotifyService_ServiceDesc, srv)
}

func _NotifyService_CreateCancellation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateCancellationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotifyServiceServer).CreateCancellation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NotifyService_CreateCancellation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotifyServiceServer).CreateCancellation(ctx, req.(*CreateCancellationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NotifyService_GetAllCancellations_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetByLeadIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotifyServiceServer).GetAllCancellations(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NotifyService_GetAllCancellations_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotifyServiceServer).GetAllCancellations(ctx, req.(*GetByLeadIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NotifyService_GetCancellationByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetByMeetingIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotifyServiceServer).GetCancellationByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NotifyService_GetCancellationByID_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotifyServiceServer).GetCancellationByID(ctx, req.(*GetByMeetingIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NotifyService_UpdateCancellation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateCancellationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotifyServiceServer).UpdateCancellation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NotifyService_UpdateCancellation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotifyServiceServer).UpdateCancellation(ctx, req.(*UpdateCancellationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NotifyService_DeleteCancellation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteByMeetingIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotifyServiceServer).DeleteCancellation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NotifyService_DeleteCancellation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotifyServiceServer).DeleteCancellation(ctx, req.(*DeleteByMeetingIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NotifyService_CreateSuccess_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateSuccessRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotifyServiceServer).CreateSuccess(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NotifyService_CreateSuccess_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotifyServiceServer).CreateSuccess(ctx, req.(*CreateSuccessRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NotifyService_GetAllSuccesses_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetByLeadIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotifyServiceServer).GetAllSuccesses(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NotifyService_GetAllSuccesses_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotifyServiceServer).GetAllSuccesses(ctx, req.(*GetByLeadIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NotifyService_GetSuccessByLeadID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetByLeadIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotifyServiceServer).GetSuccessByLeadID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NotifyService_GetSuccessByLeadID_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotifyServiceServer).GetSuccessByLeadID(ctx, req.(*GetByLeadIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NotifyService_UpdateSuccess_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateSuccessRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotifyServiceServer).UpdateSuccess(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NotifyService_UpdateSuccess_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotifyServiceServer).UpdateSuccess(ctx, req.(*UpdateSuccessRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NotifyService_DeleteSuccess_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetByLeadIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotifyServiceServer).DeleteSuccess(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NotifyService_DeleteSuccess_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotifyServiceServer).DeleteSuccess(ctx, req.(*GetByLeadIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// NotifyService_ServiceDesc is the grpc.ServiceDesc for NotifyService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var NotifyService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "notify.NotifyService",
	HandlerType: (*NotifyServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateCancellation",
			Handler:    _NotifyService_CreateCancellation_Handler,
		},
		{
			MethodName: "GetAllCancellations",
			Handler:    _NotifyService_GetAllCancellations_Handler,
		},
		{
			MethodName: "GetCancellationByID",
			Handler:    _NotifyService_GetCancellationByID_Handler,
		},
		{
			MethodName: "UpdateCancellation",
			Handler:    _NotifyService_UpdateCancellation_Handler,
		},
		{
			MethodName: "DeleteCancellation",
			Handler:    _NotifyService_DeleteCancellation_Handler,
		},
		{
			MethodName: "CreateSuccess",
			Handler:    _NotifyService_CreateSuccess_Handler,
		},
		{
			MethodName: "GetAllSuccesses",
			Handler:    _NotifyService_GetAllSuccesses_Handler,
		},
		{
			MethodName: "GetSuccessByLeadID",
			Handler:    _NotifyService_GetSuccessByLeadID_Handler,
		},
		{
			MethodName: "UpdateSuccess",
			Handler:    _NotifyService_UpdateSuccess_Handler,
		},
		{
			MethodName: "DeleteSuccess",
			Handler:    _NotifyService_DeleteSuccess_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "notify.proto",
}
