// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.1
// source: notify.proto

package notify

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	NotifyService_Cancellation_FullMethodName                 = "/notify.NotifyService/Cancellation"
	NotifyService_GetAllCancellations_FullMethodName          = "/notify.NotifyService/GetAllCancellations"
	NotifyService_GetCancellationByID_FullMethodName          = "/notify.NotifyService/GetCancellationByID"
	NotifyService_CreateSuccess_FullMethodName                = "/notify.NotifyService/CreateSuccess"
	NotifyService_GetAllSuccesses_FullMethodName              = "/notify.NotifyService/GetAllSuccesses"
	NotifyService_GetSuccessByLeadIdentifier_FullMethodName   = "/notify.NotifyService/GetSuccessByLeadIdentifier"
	NotifyService_CreateScheduled_FullMethodName              = "/notify.NotifyService/CreateScheduled"
	NotifyService_GetAllScheduled_FullMethodName              = "/notify.NotifyService/GetAllScheduled"
	NotifyService_GetScheduledByID_FullMethodName             = "/notify.NotifyService/GetScheduledByID"
	NotifyService_Rescheduled_FullMethodName                  = "/notify.NotifyService/Rescheduled"
	NotifyService_GetAllRescheduled_FullMethodName            = "/notify.NotifyService/GetAllRescheduled"
	NotifyService_GetRescheduledByID_FullMethodName           = "/notify.NotifyService/GetRescheduledByID"
	NotifyService_CreateLead_FullMethodName                   = "/notify.NotifyService/CreateLead"
	NotifyService_GetAllLeads_FullMethodName                  = "/notify.NotifyService/GetAllLeads"
	NotifyService_GetLeadByIdentifier_FullMethodName          = "/notify.NotifyService/GetLeadByIdentifier"
	NotifyService_CreateBooking_FullMethodName                = "/notify.NotifyService/CreateBooking"
	NotifyService_GetAllBookings_FullMethodName               = "/notify.NotifyService/GetAllBookings"
	NotifyService_GetBookingByID_FullMethodName               = "/notify.NotifyService/GetBookingByID"
	NotifyService_GetCounts_FullMethodName                    = "/notify.NotifyService/GetCounts"
	NotifyService_CreateDesignLeadPre10_FullMethodName        = "/notify.NotifyService/CreateDesignLeadPre10"
	NotifyService_CreateDesignLead1020_FullMethodName         = "/notify.NotifyService/CreateDesignLead1020"
	NotifyService_CreateDesignMilestone_FullMethodName        = "/notify.NotifyService/CreateDesignMilestone"
	NotifyService_CreateDesignPaymentRequest_FullMethodName   = "/notify.NotifyService/CreateDesignPaymentRequest"
	NotifyService_CreateDesignPaymentStatus_FullMethodName    = "/notify.NotifyService/CreateDesignPaymentStatus"
	NotifyService_CreateDesignDQCRequest_FullMethodName       = "/notify.NotifyService/CreateDesignDQCRequest"
	NotifyService_CreateDesignDQCStatus_FullMethodName        = "/notify.NotifyService/CreateDesignDQCStatus"
	NotifyService_CreateDesignMMTRequest_FullMethodName       = "/notify.NotifyService/CreateDesignMMTRequest"
	NotifyService_CreateDesignMMTAssign_FullMethodName        = "/notify.NotifyService/CreateDesignMMTAssign"
	NotifyService_CreateDesignMMTDocReady_FullMethodName      = "/notify.NotifyService/CreateDesignMMTDocReady"
	NotifyService_CreateDesignMeeting_FullMethodName          = "/notify.NotifyService/CreateDesignMeeting"
	NotifyService_CreateDesignAssignDesigner_FullMethodName   = "/notify.NotifyService/CreateDesignAssignDesigner"
	NotifyService_CreateDesignAssignPM_FullMethodName         = "/notify.NotifyService/CreateDesignAssignPM"
	NotifyService_CreateDesignQuote_FullMethodName            = "/notify.NotifyService/CreateDesignQuote"
	NotifyService_CreateDesignP2P_FullMethodName              = "/notify.NotifyService/CreateDesignP2P"
	NotifyService_GetDesignNotificationFeed_FullMethodName    = "/notify.NotifyService/GetDesignNotificationFeed"
	NotifyService_GetDesignNotificationCounts_FullMethodName  = "/notify.NotifyService/GetDesignNotificationCounts"
	NotifyService_GetDesignNotificationDetails_FullMethodName = "/notify.NotifyService/GetDesignNotificationDetails"
)

// NotifyServiceClient is the client API for NotifyService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type NotifyServiceClient interface {
	// Cancellation — PUT
	Cancellation(ctx context.Context, in *CancellationRequest, opts ...grpc.CallOption) (*CancellationResponse, error)
	GetAllCancellations(ctx context.Context, in *GetByLeadIdentifierRequest, opts ...grpc.CallOption) (*CancellationListResponse, error)
	GetCancellationByID(ctx context.Context, in *GetByMeetingIDRequest, opts ...grpc.CallOption) (*CancellationResponse, error)
	// Success
	CreateSuccess(ctx context.Context, in *CreateSuccessRequest, opts ...grpc.CallOption) (*SuccessResponse, error)
	GetAllSuccesses(ctx context.Context, in *GetByLeadIdentifierRequest, opts ...grpc.CallOption) (*SuccessListResponse, error)
	GetSuccessByLeadIdentifier(ctx context.Context, in *GetByLeadIdentifierRequest, opts ...grpc.CallOption) (*SuccessResponse, error)
	// Scheduled
	CreateScheduled(ctx context.Context, in *CreateScheduledRequest, opts ...grpc.CallOption) (*ScheduledResponse, error)
	GetAllScheduled(ctx context.Context, in *GetScheduledByLeadIdentifierRequest, opts ...grpc.CallOption) (*ScheduledListResponse, error)
	GetScheduledByID(ctx context.Context, in *GetScheduledByIDRequest, opts ...grpc.CallOption) (*ScheduledResponse, error)
	// Rescheduled — PUT
	Rescheduled(ctx context.Context, in *RescheduledRequest, opts ...grpc.CallOption) (*RescheduledResponse, error)
	GetAllRescheduled(ctx context.Context, in *GetRescheduledByLeadIdentifierRequest, opts ...grpc.CallOption) (*RescheduledListResponse, error)
	GetRescheduledByID(ctx context.Context, in *GetRescheduledByIDRequest, opts ...grpc.CallOption) (*RescheduledResponse, error)
	// Leads
	CreateLead(ctx context.Context, in *CreateLeadRequest, opts ...grpc.CallOption) (*LeadResponse, error)
	GetAllLeads(ctx context.Context, in *CountsRequest, opts ...grpc.CallOption) (*LeadListResponse, error)
	GetLeadByIdentifier(ctx context.Context, in *GetByLeadIdentifierRequest, opts ...grpc.CallOption) (*LeadResponse, error)
	// Booking
	CreateBooking(ctx context.Context, in *CreateBookingRequest, opts ...grpc.CallOption) (*BookingResponse, error)
	GetAllBookings(ctx context.Context, in *GetBookingByLeadIdentifierRequest, opts ...grpc.CallOption) (*BookingListResponse, error)
	GetBookingByID(ctx context.Context, in *GetBookingByIDRequest, opts ...grpc.CallOption) (*BookingResponse, error)
	// Counts
	GetCounts(ctx context.Context, in *CountsRequest, opts ...grpc.CallOption) (*CountsResponse, error)
	// 01 — Pre-10% New Lead
	CreateDesignLeadPre10(ctx context.Context, in *DesignLeadPre10Request, opts ...grpc.CallOption) (*DesignLeadPre10Response, error)
	// 02 — 10–20% Phase Entered
	CreateDesignLead1020(ctx context.Context, in *DesignLead1020Request, opts ...grpc.CallOption) (*DesignLead1020Response, error)
	// 03 — Milestone Completed
	CreateDesignMilestone(ctx context.Context, in *DesignMilestoneRequest, opts ...grpc.CallOption) (*DesignMilestoneResponse, error)
	// 04 — Payment Requested
	CreateDesignPaymentRequest(ctx context.Context, in *DesignPaymentRequestRequest, opts ...grpc.CallOption) (*DesignPaymentRequestResponse, error)
	// 05 — Payment / Sales Closure Status
	CreateDesignPaymentStatus(ctx context.Context, in *DesignPaymentStatusRequest, opts ...grpc.CallOption) (*DesignPaymentStatusResponse, error)
	// 06 — DQC Requested
	CreateDesignDQCRequest(ctx context.Context, in *DesignDQCRequestRequest, opts ...grpc.CallOption) (*DesignDQCRequestResponse, error)
	// 07 — DQC Status
	CreateDesignDQCStatus(ctx context.Context, in *DesignDQCStatusRequest, opts ...grpc.CallOption) (*DesignDQCStatusResponse, error)
	// 08 — MMT Visit Requested
	CreateDesignMMTRequest(ctx context.Context, in *DesignMMTRequestRequest, opts ...grpc.CallOption) (*DesignMMTRequestResponse, error)
	// 09 — MMT Executive Assigned
	CreateDesignMMTAssign(ctx context.Context, in *DesignMMTAssignRequest, opts ...grpc.CallOption) (*DesignMMTAssignResponse, error)
	// 10 — MMT Documents Ready
	CreateDesignMMTDocReady(ctx context.Context, in *DesignMMTDocReadyRequest, opts ...grpc.CallOption) (*DesignMMTDocReadyResponse, error)
	// 11 — Design Meeting Scheduled
	CreateDesignMeeting(ctx context.Context, in *DesignMeetingRequest, opts ...grpc.CallOption) (*DesignMeetingResponse, error)
	// 12 — Designer Reassignment
	CreateDesignAssignDesigner(ctx context.Context, in *DesignAssignDesignerRequest, opts ...grpc.CallOption) (*DesignAssignDesignerResponse, error)
	// 13 — PM Assignment
	CreateDesignAssignPM(ctx context.Context, in *DesignAssignPMRequest, opts ...grpc.CallOption) (*DesignAssignPMResponse, error)
	// 14 — New Quote
	CreateDesignQuote(ctx context.Context, in *DesignQuoteRequest, opts ...grpc.CallOption) (*DesignQuoteResponse, error)
	// 15 — P2P Completed
	CreateDesignP2P(ctx context.Context, in *DesignP2PRequest, opts ...grpc.CallOption) (*DesignP2PResponse, error)
	// 16 — Notification Feed
	GetDesignNotificationFeed(ctx context.Context, in *DesignNotificationFeedRequest, opts ...grpc.CallOption) (*DesignNotificationFeedResponse, error)
	// 17 — Notification Counts
	GetDesignNotificationCounts(ctx context.Context, in *DesignNotificationCountsRequest, opts ...grpc.CallOption) (*DesignNotificationCountsResponse, error)
	// 18 — Notification Details
	GetDesignNotificationDetails(ctx context.Context, in *DesignNotificationDetailsRequest, opts ...grpc.CallOption) (*DesignNotificationDetailsResponse, error)
}

type notifyServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewNotifyServiceClient(cc grpc.ClientConnInterface) NotifyServiceClient {
	return &notifyServiceClient{cc}
}

func (c *notifyServiceClient) Cancellation(ctx context.Context, in *CancellationRequest, opts ...grpc.CallOption) (*CancellationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CancellationResponse)
	err := c.cc.Invoke(ctx, NotifyService_Cancellation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *notifyServiceClient) GetAllCancellations(ctx context.Context, in *GetByLeadIdentifierRequest, opts ...grpc.CallOption) (*CancellationListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CancellationListResponse)
	err := c.cc.Invoke(ctx, NotifyService_GetAllCancellations_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *notifyServiceClient) GetCancellationByID(ctx context.Context, in *GetByMeetingIDRequest, opts ...grpc.CallOption) (*CancellationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CancellationResponse)
	err := c.cc.Invoke(ctx, NotifyService_GetCancellationByID_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *notifyServiceClient) CreateSuccess(ctx context.Context, in *CreateSuccessRequest, opts ...grpc.CallOption) (*SuccessResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SuccessResponse)
	err := c.cc.Invoke(ctx, NotifyService_CreateSuccess_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *notifyServiceClient) GetAllSuccesses(ctx context.Context, in *GetByLeadIdentifierRequest, opts ...grpc.CallOption) (*SuccessListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SuccessListResponse)
	err := c.cc.Invoke(ctx, NotifyService_GetAllSuccesses_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *notifyServiceClient) GetSuccessByLeadIdentifier(ctx context.Context, in *GetByLeadIdentifierRequest, opts ...grpc.CallOption) (*SuccessResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SuccessResponse)
	err := c.cc.Invoke(ctx, NotifyService_GetSuccessByLeadIdentifier_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *notifyServiceClient) CreateScheduled(ctx context.Context, in *CreateScheduledRequest, opts ...grpc.CallOption) (*ScheduledResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ScheduledResponse)
	err := c.cc.Invoke(ctx, NotifyService_CreateScheduled_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *notifyServiceClient) GetAllScheduled(ctx context.Context, in *GetScheduledByLeadIdentifierRequest, opts ...grpc.CallOption) (*ScheduledListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ScheduledListResponse)
	err := c.cc.Invoke(ctx, NotifyService_GetAllScheduled_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *notifyServiceClient) GetScheduledByID(ctx context.Context, in *GetScheduledByIDRequest, opts ...grpc.CallOption) (*ScheduledResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ScheduledResponse)
	err := c.cc.Invoke(ctx, NotifyService_GetScheduledByID_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *notifyServiceClient) Rescheduled(ctx context.Context, in *RescheduledRequest, opts ...grpc.CallOption) (*RescheduledResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RescheduledResponse)
	err := c.cc.Invoke(ctx, NotifyService_Rescheduled_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *notifyServiceClient) GetAllRescheduled(ctx context.Context, in *GetRescheduledByLeadIdentifierRequest, opts ...grpc.CallOption) (*RescheduledListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RescheduledListResponse)
	err := c.cc.Invoke(ctx, NotifyService_GetAllRescheduled_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *notifyServiceClient) GetRescheduledByID(ctx context.Context, in *GetRescheduledByIDRequest, opts ...grpc.CallOption) (*RescheduledResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RescheduledResponse)
	err := c.cc.Invoke(ctx, NotifyService_GetRescheduledByID_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *notifyServiceClient) CreateLead(ctx context.Context, in *CreateLeadRequest, opts ...grpc.CallOption) (*LeadResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LeadResponse)
	err := c.cc.Invoke(ctx, NotifyService_CreateLead_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *notifyServiceClient) GetAllLeads(ctx context.Context, in *CountsRequest, opts ...grpc.CallOption) (*LeadListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LeadListResponse)
	err := c.cc.Invoke(ctx, NotifyService_GetAllLeads_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *notifyServiceClient) GetLeadByIdentifier(ctx context.Context, in *GetByLeadIdentifierRequest, opts ...grpc.CallOption) (*LeadResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LeadResponse)
	err := c.cc.Invoke(ctx, NotifyService_GetLeadByIdentifier_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *notifyServiceClient) CreateBooking(ctx context.Context, in *CreateBookingRequest, opts ...grpc.CallOption) (*BookingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BookingResponse)
	err := c.cc.Invoke(ctx, NotifyService_CreateBooking_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *notifyServiceClient) GetAllBookings(ctx context.Context, in *GetBookingByLeadIdentifierRequest, opts ...grpc.CallOption) (*BookingListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BookingListResponse)
	err := c.cc.Invoke(ctx, NotifyService_GetAllBookings_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *notifyServiceClient) GetBookingByID(ctx context.Context, in *GetBookingByIDRequest, opts ...grpc.CallOption) (*BookingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BookingResponse)
	err := c.cc.Invoke(ctx, NotifyService_GetBookingByID_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *notifyServiceClient) GetCounts(ctx context.Context, in *CountsRequest, opts ...grpc.CallOption) (*CountsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CountsResponse)
	err := c.cc.Invoke(ctx, NotifyService_GetCounts_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *notifyServiceClient) CreateDesignLeadPre10(ctx context.Context, in *DesignLeadPre10Request, opts ...grpc.CallOption) (*DesignLeadPre10Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DesignLeadPre10Response)
	err := c.cc.Invoke(ctx, NotifyService_CreateDesignLeadPre10_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *notifyServiceClient) CreateDesignLead1020(ctx context.Context, in *DesignLead1020Request, opts ...grpc.CallOption) (*DesignLead1020Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DesignLead1020Response)
	err := c.cc.Invoke(ctx, NotifyService_CreateDesignLead1020_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *notifyServiceClient) CreateDesignMilestone(ctx context.Context, in *DesignMilestoneRequest, opts ...grpc.CallOption) (*DesignMilestoneResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DesignMilestoneResponse)
	err := c.cc.Invoke(ctx, NotifyService_CreateDesignMilestone_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *notifyServiceClient) CreateDesignPaymentRequest(ctx context.Context, in *DesignPaymentRequestRequest, opts ...grpc.CallOption) (*DesignPaymentRequestResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DesignPaymentRequestResponse)
	err := c.cc.Invoke(ctx, NotifyService_CreateDesignPaymentRequest_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *notifyServiceClient) CreateDesignPaymentStatus(ctx context.Context, in *DesignPaymentStatusRequest, opts ...grpc.CallOption) (*DesignPaymentStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DesignPaymentStatusResponse)
	err := c.cc.Invoke(ctx, NotifyService_CreateDesignPaymentStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *notifyServiceClient) CreateDesignDQCRequest(ctx context.Context, in *DesignDQCRequestRequest, opts ...grpc.CallOption) (*DesignDQCRequestResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DesignDQCRequestResponse)
	err := c.cc.Invoke(ctx, NotifyService_CreateDesignDQCRequest_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *notifyServiceClient) CreateDesignDQCStatus(ctx context.Context, in *DesignDQCStatusRequest, opts ...grpc.CallOption) (*DesignDQCStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DesignDQCStatusResponse)
	err := c.cc.Invoke(ctx, NotifyService_CreateDesignDQCStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *notifyServiceClient) CreateDesignMMTRequest(ctx context.Context, in *DesignMMTRequestRequest, opts ...grpc.CallOption) (*DesignMMTRequestResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DesignMMTRequestResponse)
	err := c.cc.Invoke(ctx, NotifyService_CreateDesignMMTRequest_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *notifyServiceClient) CreateDesignMMTAssign(ctx context.Context, in *DesignMMTAssignRequest, opts ...grpc.CallOption) (*DesignMMTAssignResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DesignMMTAssignResponse)
	err := c.cc.Invoke(ctx, NotifyService_CreateDesignMMTAssign_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *notifyServiceClient) CreateDesignMMTDocReady(ctx context.Context, in *DesignMMTDocReadyRequest, opts ...grpc.CallOption) (*DesignMMTDocReadyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DesignMMTDocReadyResponse)
	err := c.cc.Invoke(ctx, NotifyService_CreateDesignMMTDocReady_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *notifyServiceClient) CreateDesignMeeting(ctx context.Context, in *DesignMeetingRequest, opts ...grpc.CallOption) (*DesignMeetingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DesignMeetingResponse)
	err := c.cc.Invoke(ctx, NotifyService_CreateDesignMeeting_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *notifyServiceClient) CreateDesignAssignDesigner(ctx context.Context, in *DesignAssignDesignerRequest, opts ...grpc.CallOption) (*DesignAssignDesignerResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DesignAssignDesignerResponse)
	err := c.cc.Invoke(ctx, NotifyService_CreateDesignAssignDesigner_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *notifyServiceClient) CreateDesignAssignPM(ctx context.Context, in *DesignAssignPMRequest, opts ...grpc.CallOption) (*DesignAssignPMResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DesignAssignPMResponse)
	err := c.cc.Invoke(ctx, NotifyService_CreateDesignAssignPM_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *notifyServiceClient) CreateDesignQuote(ctx context.Context, in *DesignQuoteRequest, opts ...grpc.CallOption) (*DesignQuoteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DesignQuoteResponse)
	err := c.cc.Invoke(ctx, NotifyService_CreateDesignQuote_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *notifyServiceClient) CreateDesignP2P(ctx context.Context, in *DesignP2PRequest, opts ...grpc.CallOption) (*DesignP2PResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DesignP2PResponse)
	err := c.cc.Invoke(ctx, NotifyService_CreateDesignP2P_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *notifyServiceClient) GetDesignNotificationFeed(ctx context.Context, in *DesignNotificationFeedRequest, opts ...grpc.CallOption) (*DesignNotificationFeedResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DesignNotificationFeedResponse)
	err := c.cc.Invoke(ctx, NotifyService_GetDesignNotificationFeed_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *notifyServiceClient) GetDesignNotificationCounts(ctx context.Context, in *DesignNotificationCountsRequest, opts ...grpc.CallOption) (*DesignNotificationCountsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DesignNotificationCountsResponse)
	err := c.cc.Invoke(ctx, NotifyService_GetDesignNotificationCounts_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *notifyServiceClient) GetDesignNotificationDetails(ctx context.Context, in *DesignNotificationDetailsRequest, opts ...grpc.CallOption) (*DesignNotificationDetailsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DesignNotificationDetailsResponse)
	err := c.cc.Invoke(ctx, NotifyService_GetDesignNotificationDetails_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NotifyServiceServer is the server API for NotifyService service.
// All implementations must embed UnimplementedNotifyServiceServer
// for forward compatibility.
type NotifyServiceServer interface {
	// Cancellation — PUT
	Cancellation(context.Context, *CancellationRequest) (*CancellationResponse, error)
	GetAllCancellations(context.Context, *GetByLeadIdentifierRequest) (*CancellationListResponse, error)
	GetCancellationByID(context.Context, *GetByMeetingIDRequest) (*CancellationResponse, error)
	// Success
	CreateSuccess(context.Context, *CreateSuccessRequest) (*SuccessResponse, error)
	GetAllSuccesses(context.Context, *GetByLeadIdentifierRequest) (*SuccessListResponse, error)
	GetSuccessByLeadIdentifier(context.Context, *GetByLeadIdentifierRequest) (*SuccessResponse, error)
	// Scheduled
	CreateScheduled(context.Context, *CreateScheduledRequest) (*ScheduledResponse, error)
	GetAllScheduled(context.Context, *GetScheduledByLeadIdentifierRequest) (*ScheduledListResponse, error)
	GetScheduledByID(context.Context, *GetScheduledByIDRequest) (*ScheduledResponse, error)
	// Rescheduled — PUT
	Rescheduled(context.Context, *RescheduledRequest) (*RescheduledResponse, error)
	GetAllRescheduled(context.Context, *GetRescheduledByLeadIdentifierRequest) (*RescheduledListResponse, error)
	GetRescheduledByID(context.Context, *GetRescheduledByIDRequest) (*RescheduledResponse, error)
	// Leads
	CreateLead(context.Context, *CreateLeadRequest) (*LeadResponse, error)
	GetAllLeads(context.Context, *CountsRequest) (*LeadListResponse, error)
	GetLeadByIdentifier(context.Context, *GetByLeadIdentifierRequest) (*LeadResponse, error)
	// Booking
	CreateBooking(context.Context, *CreateBookingRequest) (*BookingResponse, error)
	GetAllBookings(context.Context, *GetBookingByLeadIdentifierRequest) (*BookingListResponse, error)
	GetBookingByID(context.Context, *GetBookingByIDRequest) (*BookingResponse, error)
	// Counts
	GetCounts(context.Context, *CountsRequest) (*CountsResponse, error)
	// 01 — Pre-10% New Lead
	CreateDesignLeadPre10(context.Context, *DesignLeadPre10Request) (*DesignLeadPre10Response, error)
	// 02 — 10–20% Phase Entered
	CreateDesignLead1020(context.Context, *DesignLead1020Request) (*DesignLead1020Response, error)
	// 03 — Milestone Completed
	CreateDesignMilestone(context.Context, *DesignMilestoneRequest) (*DesignMilestoneResponse, error)
	// 04 — Payment Requested
	CreateDesignPaymentRequest(context.Context, *DesignPaymentRequestRequest) (*DesignPaymentRequestResponse, error)
	// 05 — Payment / Sales Closure Status
	CreateDesignPaymentStatus(context.Context, *DesignPaymentStatusRequest) (*DesignPaymentStatusResponse, error)
	// 06 — DQC Requested
	CreateDesignDQCRequest(context.Context, *DesignDQCRequestRequest) (*DesignDQCRequestResponse, error)
	// 07 — DQC Status
	CreateDesignDQCStatus(context.Context, *DesignDQCStatusRequest) (*DesignDQCStatusResponse, error)
	// 08 — MMT Visit Requested
	CreateDesignMMTRequest(context.Context, *DesignMMTRequestRequest) (*DesignMMTRequestResponse, error)
	// 09 — MMT Executive Assigned
	CreateDesignMMTAssign(context.Context, *DesignMMTAssignRequest) (*DesignMMTAssignResponse, error)
	// 10 — MMT Documents Ready
	CreateDesignMMTDocReady(context.Context, *DesignMMTDocReadyRequest) (*DesignMMTDocReadyResponse, error)
	// 11 — Design Meeting Scheduled
	CreateDesignMeeting(context.Context, *DesignMeetingRequest) (*DesignMeetingResponse, error)
	// 12 — Designer Reassignment
	CreateDesignAssignDesigner(context.Context, *DesignAssignDesignerRequest) (*DesignAssignDesignerResponse, error)
	// 13 — PM Assignment
	CreateDesignAssignPM(context.Context, *DesignAssignPMRequest) (*DesignAssignPMResponse, error)
	// 14 — New Quote
	CreateDesignQuote(context.Context, *DesignQuoteRequest) (*DesignQuoteResponse, error)
	// 15 — P2P Completed
	CreateDesignP2P(context.Context, *DesignP2PRequest) (*DesignP2PResponse, error)
	// 16 — Notification Feed
	GetDesignNotificationFeed(context.Context, *DesignNotificationFeedRequest) (*DesignNotificationFeedResponse, error)
	// 17 — Notification Counts
	GetDesignNotificationCounts(context.Context, *DesignNotificationCountsRequest) (*DesignNotificationCountsResponse, error)
	// 18 — Notification Details
	GetDesignNotificationDetails(context.Context, *DesignNotificationDetailsRequest) (*DesignNotificationDetailsResponse, error)
	mustEmbedUnimplementedNotifyServiceServer()
}

// UnimplementedNotifyServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedNotifyServiceServer struct{}

func (UnimplementedNotifyServiceServer) Cancellation(context.Context, *CancellationRequest) (*CancellationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Cancellation not implemented")
}
func (UnimplementedNotifyServiceServer) GetAllCancellations(context.Context, *GetByLeadIdentifierRequest) (*CancellationListResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAllCancellations not implemented")
}
func (UnimplementedNotifyServiceServer) GetCancellationByID(context.Context, *GetByMeetingIDRequest) (*CancellationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCancellationByID not implemented")
}
func (UnimplementedNotifyServiceServer) CreateSuccess(context.Context, *CreateSuccessRequest) (*SuccessResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateSuccess not implemented")
}
func (UnimplementedNotifyServiceServer) GetAllSuccesses(context.Context, *GetByLeadIdentifierRequest) (*SuccessListResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAllSuccesses not implemented")
}
func (UnimplementedNotifyServiceServer) GetSuccessByLeadIdentifier(context.Context, *GetByLeadIdentifierRequest) (*SuccessResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSuccessByLeadIdentifier not implemented")
}
func (UnimplementedNotifyServiceServer) CreateScheduled(context.Context, *CreateScheduledRequest) (*ScheduledResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateScheduled not implemented")
}
func (UnimplementedNotifyServiceServer) GetAllScheduled(context.Context, *GetScheduledByLeadIdentifierRequest) (*ScheduledListResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAllScheduled not implemented")
}
func (UnimplementedNotifyServiceServer) GetScheduledByID(context.Context, *GetScheduledByIDRequest) (*ScheduledResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetScheduledByID not implemented")
}
func (UnimplementedNotifyServiceServer) Rescheduled(context.Context, *RescheduledRequest) (*RescheduledResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Rescheduled not implemented")
}
func (UnimplementedNotifyServiceServer) GetAllRescheduled(context.Context, *GetRescheduledByLeadIdentifierRequest) (*RescheduledListResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAllRescheduled not implemented")
}
func (UnimplementedNotifyServiceServer) GetRescheduledByID(context.Context, *GetRescheduledByIDRequest) (*RescheduledResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetRescheduledByID not implemented")
}
func (UnimplementedNotifyServiceServer) CreateLead(context.Context, *CreateLeadRequest) (*LeadResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateLead not implemented")
}
func (UnimplementedNotifyServiceServer) GetAllLeads(context.Context, *CountsRequest) (*LeadListResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAllLeads not implemented")
}
func (UnimplementedNotifyServiceServer) GetLeadByIdentifier(context.Context, *GetByLeadIdentifierRequest) (*LeadResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetLeadByIdentifier not implemented")
}
func (UnimplementedNotifyServiceServer) CreateBooking(context.Context, *CreateBookingRequest) (*BookingResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateBooking not implemented")
}
func (UnimplementedNotifyServiceServer) GetAllBookings(context.Context, *GetBookingByLeadIdentifierRequest) (*BookingListResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAllBookings not implemented")
}
func (UnimplementedNotifyServiceServer) GetBookingByID(context.Context, *GetBookingByIDRequest) (*BookingResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetBookingByID not implemented")
}
func (UnimplementedNotifyServiceServer) GetCounts(context.Context, *CountsRequest) (*CountsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCounts not implemented")
}
func (UnimplementedNotifyServiceServer) CreateDesignLeadPre10(context.Context, *DesignLeadPre10Request) (*DesignLeadPre10Response, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateDesignLeadPre10 not implemented")
}
func (UnimplementedNotifyServiceServer) CreateDesignLead1020(context.Context, *DesignLead1020Request) (*DesignLead1020Response, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateDesignLead1020 not implemented")
}
func (UnimplementedNotifyServiceServer) CreateDesignMilestone(context.Context, *DesignMilestoneRequest) (*DesignMilestoneResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateDesignMilestone not implemented")
}
func (UnimplementedNotifyServiceServer) CreateDesignPaymentRequest(context.Context, *DesignPaymentRequestRequest) (*DesignPaymentRequestResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateDesignPaymentRequest not implemented")
}
func (UnimplementedNotifyServiceServer) CreateDesignPaymentStatus(context.Context, *DesignPaymentStatusRequest) (*DesignPaymentStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateDesignPaymentStatus not implemented")
}
func (UnimplementedNotifyServiceServer) CreateDesignDQCRequest(context.Context, *DesignDQCRequestRequest) (*DesignDQCRequestResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateDesignDQCRequest not implemented")
}
func (UnimplementedNotifyServiceServer) CreateDesignDQCStatus(context.Context, *DesignDQCStatusRequest) (*DesignDQCStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateDesignDQCStatus not implemented")
}
func (UnimplementedNotifyServiceServer) CreateDesignMMTRequest(context.Context, *DesignMMTRequestRequest) (*DesignMMTRequestResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateDesignMMTRequest not implemented")
}
func (UnimplementedNotifyServiceServer) CreateDesignMMTAssign(context.Context, *DesignMMTAssignRequest) (*DesignMMTAssignResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateDesignMMTAssign not implemented")
}
func (UnimplementedNotifyServiceServer) CreateDesignMMTDocReady(context.Context, *DesignMMTDocReadyRequest) (*DesignMMTDocReadyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateDesignMMTDocReady not implemented")
}
func (UnimplementedNotifyServiceServer) CreateDesignMeeting(context.Context, *DesignMeetingRequest) (*DesignMeetingResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateDesignMeeting not implemented")
}
func (UnimplementedNotifyServiceServer) CreateDesignAssignDesigner(context.Context, *DesignAssignDesignerRequest) (*DesignAssignDesignerResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateDesignAssignDesigner not implemented")
}
func (UnimplementedNotifyServiceServer) CreateDesignAssignPM(context.Context, *DesignAssignPMRequest) (*DesignAssignPMResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateDesignAssignPM not implemented")
}
func (UnimplementedNotifyServiceServer) CreateDesignQuote(context.Context, *DesignQuoteRequest) (*DesignQuoteResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateDesignQuote not implemented")
}
func (UnimplementedNotifyServiceServer) CreateDesignP2P(context.Context, *DesignP2PRequest) (*DesignP2PResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateDesignP2P not implemented")
}
func (UnimplementedNotifyServiceServer) GetDesignNotificationFeed(context.Context, *DesignNotificationFeedRequest) (*DesignNotificationFeedResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetDesignNotificationFeed not implemented")
}
func (UnimplementedNotifyServiceServer) GetDesignNotificationCounts(context.Context, *DesignNotificationCountsRequest) (*DesignNotificationCountsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetDesignNotificationCounts not implemented")
}
func (UnimplementedNotifyServiceServer) GetDesignNotificationDetails(context.Context, *DesignNotificationDetailsRequest) (*DesignNotificationDetailsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetDesignNotificationDetails not implemented")
}
func (UnimplementedNotifyServiceServer) mustEmbedUnimplementedNotifyServiceServer() {}
func (UnimplementedNotifyServiceServer) testEmbeddedByValue()                       {}

// UnsafeNotifyServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NotifyServiceServer will
// result in compilation errors.
type UnsafeNotifyServiceServer interface {
	mustEmbedUnimplementedNotifyServiceServer()
}

func RegisterNotifyServiceServer(s grpc.ServiceRegistrar, srv NotifyServiceServer) {
	// If the following call panics, it indicates UnimplementedNotifyServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&NotifyService_ServiceDesc, srv)
}

func _NotifyService_Cancellation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CancellationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotifyServiceServer).Cancellation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NotifyService_Cancellation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotifyServiceServer).Cancellation(ctx, req.(*CancellationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NotifyService_GetAllCancellations_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetByLeadIdentifierRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotifyServiceServer).GetAllCancellations(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NotifyService_GetAllCancellations_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotifyServiceServer).GetAllCancellations(ctx, req.(*GetByLeadIdentifierRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NotifyService_GetCancellationByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetByMeetingIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotifyServiceServer).GetCancellationByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NotifyService_GetCancellationByID_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotifyServiceServer).GetCancellationByID(ctx, req.(*GetByMeetingIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NotifyService_CreateSuccess_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateSuccessRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotifyServiceServer).CreateSuccess(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NotifyService_CreateSuccess_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotifyServiceServer).CreateSuccess(ctx, req.(*CreateSuccessRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NotifyService_GetAllSuccesses_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetByLeadIdentifierRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotifyServiceServer).GetAllSuccesses(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NotifyService_GetAllSuccesses_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotifyServiceServer).GetAllSuccesses(ctx, req.(*GetByLeadIdentifierRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NotifyService_GetSuccessByLeadIdentifier_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetByLeadIdentifierRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotifyServiceServer).GetSuccessByLeadIdentifier(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NotifyService_GetSuccessByLeadIdentifier_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotifyServiceServer).GetSuccessByLeadIdentifier(ctx, req.(*GetByLeadIdentifierRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NotifyService_CreateScheduled_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateScheduledRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotifyServiceServer).CreateScheduled(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NotifyService_CreateScheduled_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotifyServiceServer).CreateScheduled(ctx, req.(*CreateScheduledRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NotifyService_GetAllScheduled_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetScheduledByLeadIdentifierRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotifyServiceServer).GetAllScheduled(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NotifyService_GetAllScheduled_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotifyServiceServer).GetAllScheduled(ctx, req.(*GetScheduledByLeadIdentifierRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NotifyService_GetScheduledByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetScheduledByIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotifyServiceServer).GetScheduledByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NotifyService_GetScheduledByID_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotifyServiceServer).GetScheduledByID(ctx, req.(*GetScheduledByIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NotifyService_Rescheduled_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RescheduledRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotifyServiceServer).Rescheduled(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NotifyService_Rescheduled_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotifyServiceServer).Rescheduled(ctx, req.(*RescheduledRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NotifyService_GetAllRescheduled_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRescheduledByLeadIdentifierRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotifyServiceServer).GetAllRescheduled(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NotifyService_GetAllRescheduled_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotifyServiceServer).GetAllRescheduled(ctx, req.(*GetRescheduledByLeadIdentifierRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NotifyService_GetRescheduledByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRescheduledByIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotifyServiceServer).GetRescheduledByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NotifyService_GetRescheduledByID_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotifyServiceServer).GetRescheduledByID(ctx, req.(*GetRescheduledByIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NotifyService_CreateLead_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateLeadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotifyServiceServer).CreateLead(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NotifyService_CreateLead_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotifyServiceServer).CreateLead(ctx, req.(*CreateLeadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NotifyService_GetAllLeads_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CountsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotifyServiceServer).GetAllLeads(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NotifyService_GetAllLeads_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotifyServiceServer).GetAllLeads(ctx, req.(*CountsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NotifyService_GetLeadByIdentifier_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetByLeadIdentifierRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotifyServiceServer).GetLeadByIdentifier(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NotifyService_GetLeadByIdentifier_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotifyServiceServer).GetLeadByIdentifier(ctx, req.(*GetByLeadIdentifierRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NotifyService_CreateBooking_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateBookingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotifyServiceServer).CreateBooking(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NotifyService_CreateBooking_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotifyServiceServer).CreateBooking(ctx, req.(*CreateBookingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NotifyService_GetAllBookings_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBookingByLeadIdentifierRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotifyServiceServer).GetAllBookings(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NotifyService_GetAllBookings_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotifyServiceServer).GetAllBookings(ctx, req.(*GetBookingByLeadIdentifierRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NotifyService_GetBookingByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBookingByIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotifyServiceServer).GetBookingByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NotifyService_GetBookingByID_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotifyServiceServer).GetBookingByID(ctx, req.(*GetBookingByIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NotifyService_GetCounts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CountsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotifyServiceServer).GetCounts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NotifyService_GetCounts_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotifyServiceServer).GetCounts(ctx, req.(*CountsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NotifyService_CreateDesignLeadPre10_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DesignLeadPre10Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotifyServiceServer).CreateDesignLeadPre10(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NotifyService_CreateDesignLeadPre10_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotifyServiceServer).CreateDesignLeadPre10(ctx, req.(*DesignLeadPre10Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _NotifyService_CreateDesignLead1020_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DesignLead1020Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotifyServiceServer).CreateDesignLead1020(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NotifyService_CreateDesignLead1020_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotifyServiceServer).CreateDesignLead1020(ctx, req.(*DesignLead1020Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _NotifyService_CreateDesignMilestone_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DesignMilestoneRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotifyServiceServer).CreateDesignMilestone(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NotifyService_CreateDesignMilestone_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotifyServiceServer).CreateDesignMilestone(ctx, req.(*DesignMilestoneRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NotifyService_CreateDesignPaymentRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DesignPaymentRequestRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotifyServiceServer).CreateDesignPaymentRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NotifyService_CreateDesignPaymentRequest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotifyServiceServer).CreateDesignPaymentRequest(ctx, req.(*DesignPaymentRequestRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NotifyService_CreateDesignPaymentStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DesignPaymentStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotifyServiceServer).CreateDesignPaymentStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NotifyService_CreateDesignPaymentStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotifyServiceServer).CreateDesignPaymentStatus(ctx, req.(*DesignPaymentStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NotifyService_CreateDesignDQCRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DesignDQCRequestRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotifyServiceServer).CreateDesignDQCRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NotifyService_CreateDesignDQCRequest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotifyServiceServer).CreateDesignDQCRequest(ctx, req.(*DesignDQCRequestRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NotifyService_CreateDesignDQCStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DesignDQCStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotifyServiceServer).CreateDesignDQCStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NotifyService_CreateDesignDQCStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotifyServiceServer).CreateDesignDQCStatus(ctx, req.(*DesignDQCStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NotifyService_CreateDesignMMTRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DesignMMTRequestRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotifyServiceServer).CreateDesignMMTRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NotifyService_CreateDesignMMTRequest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotifyServiceServer).CreateDesignMMTRequest(ctx, req.(*DesignMMTRequestRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NotifyService_CreateDesignMMTAssign_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DesignMMTAssignRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotifyServiceServer).CreateDesignMMTAssign(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NotifyService_CreateDesignMMTAssign_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotifyServiceServer).CreateDesignMMTAssign(ctx, req.(*DesignMMTAssignRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NotifyService_CreateDesignMMTDocReady_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DesignMMTDocReadyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotifyServiceServer).CreateDesignMMTDocReady(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NotifyService_CreateDesignMMTDocReady_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotifyServiceServer).CreateDesignMMTDocReady(ctx, req.(*DesignMMTDocReadyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NotifyService_CreateDesignMeeting_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DesignMeetingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotifyServiceServer).CreateDesignMeeting(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NotifyService_CreateDesignMeeting_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotifyServiceServer).CreateDesignMeeting(ctx, req.(*DesignMeetingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NotifyService_CreateDesignAssignDesigner_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DesignAssignDesignerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotifyServiceServer).CreateDesignAssignDesigner(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NotifyService_CreateDesignAssignDesigner_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotifyServiceServer).CreateDesignAssignDesigner(ctx, req.(*DesignAssignDesignerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NotifyService_CreateDesignAssignPM_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DesignAssignPMRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotifyServiceServer).CreateDesignAssignPM(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NotifyService_CreateDesignAssignPM_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotifyServiceServer).CreateDesignAssignPM(ctx, req.(*DesignAssignPMRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NotifyService_CreateDesignQuote_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DesignQuoteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotifyServiceServer).CreateDesignQuote(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NotifyService_CreateDesignQuote_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotifyServiceServer).CreateDesignQuote(ctx, req.(*DesignQuoteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NotifyService_CreateDesignP2P_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DesignP2PRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotifyServiceServer).CreateDesignP2P(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NotifyService_CreateDesignP2P_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotifyServiceServer).CreateDesignP2P(ctx, req.(*DesignP2PRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NotifyService_GetDesignNotificationFeed_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DesignNotificationFeedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotifyServiceServer).GetDesignNotificationFeed(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NotifyService_GetDesignNotificationFeed_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotifyServiceServer).GetDesignNotificationFeed(ctx, req.(*DesignNotificationFeedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NotifyService_GetDesignNotificationCounts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DesignNotificationCountsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotifyServiceServer).GetDesignNotificationCounts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NotifyService_GetDesignNotificationCounts_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotifyServiceServer).GetDesignNotificationCounts(ctx, req.(*DesignNotificationCountsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NotifyService_GetDesignNotificationDetails_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DesignNotificationDetailsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotifyServiceServer).GetDesignNotificationDetails(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NotifyService_GetDesignNotificationDetails_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotifyServiceServer).GetDesignNotificationDetails(ctx, req.(*DesignNotificationDetailsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// NotifyService_ServiceDesc is the grpc.ServiceDesc for NotifyService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var NotifyService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "notify.NotifyService",
	HandlerType: (*NotifyServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Cancellation",
			Handler:    _NotifyService_Cancellation_Handler,
		},
		{
			MethodName: "GetAllCancellations",
			Handler:    _NotifyService_GetAllCancellations_Handler,
		},
		{
			MethodName: "GetCancellationByID",
			Handler:    _NotifyService_GetCancellationByID_Handler,
		},
		{
			MethodName: "CreateSuccess",
			Handler:    _NotifyService_CreateSuccess_Handler,
		},
		{
			MethodName: "GetAllSuccesses",
			Handler:    _NotifyService_GetAllSuccesses_Handler,
		},
		{
			MethodName: "GetSuccessByLeadIdentifier",
			Handler:    _NotifyService_GetSuccessByLeadIdentifier_Handler,
		},
		{
			MethodName: "CreateScheduled",
			Handler:    _NotifyService_CreateScheduled_Handler,
		},
		{
			MethodName: "GetAllScheduled",
			Handler:    _NotifyService_GetAllScheduled_Handler,
		},
		{
			MethodName: "GetScheduledByID",
			Handler:    _NotifyService_GetScheduledByID_Handler,
		},
		{
			MethodName: "Rescheduled",
			Handler:    _NotifyService_Rescheduled_Handler,
		},
		{
			MethodName: "GetAllRescheduled",
			Handler:    _NotifyService_GetAllRescheduled_Handler,
		},
		{
			MethodName: "GetRescheduledByID",
			Handler:    _NotifyService_GetRescheduledByID_Handler,
		},
		{
			MethodName: "CreateLead",
			Handler:    _NotifyService_CreateLead_Handler,
		},
		{
			MethodName: "GetAllLeads",
			Handler:    _NotifyService_GetAllLeads_Handler,
		},
		{
			MethodName: "GetLeadByIdentifier",
			Handler:    _NotifyService_GetLeadByIdentifier_Handler,
		},
		{
			MethodName: "CreateBooking",
			Handler:    _NotifyService_CreateBooking_Handler,
		},
		{
			MethodName: "GetAllBookings",
			Handler:    _NotifyService_GetAllBookings_Handler,
		},
		{
			MethodName: "GetBookingByID",
			Handler:    _NotifyService_GetBookingByID_Handler,
		},
		{
			MethodName: "GetCounts",
			Handler:    _NotifyService_GetCounts_Handler,
		},
		{
			MethodName: "CreateDesignLeadPre10",
			Handler:    _NotifyService_CreateDesignLeadPre10_Handler,
		},
		{
			MethodName: "CreateDesignLead1020",
			Handler:    _NotifyService_CreateDesignLead1020_Handler,
		},
		{
			MethodName: "CreateDesignMilestone",
			Handler:    _NotifyService_CreateDesignMilestone_Handler,
		},
		{
			MethodName: "CreateDesignPaymentRequest",
			Handler:    _NotifyService_CreateDesignPaymentRequest_Handler,
		},
		{
			MethodName: "CreateDesignPaymentStatus",
			Handler:    _NotifyService_CreateDesignPaymentStatus_Handler,
		},
		{
			MethodName: "CreateDesignDQCRequest",
			Handler:    _NotifyService_CreateDesignDQCRequest_Handler,
		},
		{
			MethodName: "CreateDesignDQCStatus",
			Handler:    _NotifyService_CreateDesignDQCStatus_Handler,
		},
		{
			MethodName: "CreateDesignMMTRequest",
			Handler:    _NotifyService_CreateDesignMMTRequest_Handler,
		},
		{
			MethodName: "CreateDesignMMTAssign",
			Handler:    _NotifyService_CreateDesignMMTAssign_Handler,
		},
		{
			MethodName: "CreateDesignMMTDocReady",
			Handler:    _NotifyService_CreateDesignMMTDocReady_Handler,
		},
		{
			MethodName: "CreateDesignMeeting",
			Handler:    _NotifyService_CreateDesignMeeting_Handler,
		},
		{
			MethodName: "CreateDesignAssignDesigner",
			Handler:    _NotifyService_CreateDesignAssignDesigner_Handler,
		},
		{
			MethodName: "CreateDesignAssignPM",
			Handler:    _NotifyService_CreateDesignAssignPM_Handler,
		},
		{
			MethodName: "CreateDesignQuote",
			Handler:    _NotifyService_CreateDesignQuote_Handler,
		},
		{
			MethodName: "CreateDesignP2P",
			Handler:    _NotifyService_CreateDesignP2P_Handler,
		},
		{
			MethodName: "GetDesignNotificationFeed",
			Handler:    _NotifyService_GetDesignNotificationFeed_Handler,
		},
		{
			MethodName: "GetDesignNotificationCounts",
			Handler:    _NotifyService_GetDesignNotificationCounts_Handler,
		},
		{
			MethodName: "GetDesignNotificationDetails",
			Handler:    _NotifyService_GetDesignNotificationDetails_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "notify.proto",
}
