// Hand-written gRPC-Gateway registration.
// Normally generated by: protoc-gen-grpc-gateway
// Registers all NotifyService RPCs as HTTP endpoints via the gateway mux.

package notify

import (
	"context"
	"net/http"

	"github.com/grpc-ecosystem/grpc-gateway/v2/runtime"
	"google.golang.org/grpc"
)

// RegisterNotifyServiceHandlerFromEndpoint dials the gRPC server at grpcEndpoint
// and registers all HTTP routes on mux.
func RegisterNotifyServiceHandlerFromEndpoint(
	ctx context.Context,
	mux *runtime.ServeMux,
	grpcEndpoint string,
	opts []grpc.DialOption,
) error {
	conn, err := grpc.NewClient(grpcEndpoint, opts...)
	if err != nil {
		return err
	}
	go func() {
		<-ctx.Done()
		conn.Close()
	}()
	return RegisterNotifyServiceHandler(ctx, mux, conn)
}

// RegisterNotifyServiceHandler registers all routes on an existing ClientConn.
func RegisterNotifyServiceHandler(
	ctx context.Context,
	mux *runtime.ServeMux,
	conn *grpc.ClientConn,
) error {
	client := NewNotifyServiceClient(conn)
	codec := new(runtime.JSONPb)

	// ---- Cancellation endpoints ----------------------------------------

	// POST /v1/meetings/cancellation
	if err := mux.HandlePath("POST", "/v1/meetings/cancellation",
		func(w http.ResponseWriter, r *http.Request, _ map[string]string) {
			var req CreateCancellationRequest
			if err := codec.NewDecoder(r.Body).Decode(&req); err != nil {
				http.Error(w, err.Error(), http.StatusBadRequest)
				return
			}
			resp, err := client.CreateCancellation(ctx, &req)
			writeResponse(w, resp, err)
		},
	); err != nil {
		return err
	}

	// GET /v1/meetings/cancellation?lead_id=
	if err := mux.HandlePath("GET", "/v1/meetings/cancellation",
		func(w http.ResponseWriter, r *http.Request, _ map[string]string) {
			var req GetByLeadIDRequest
			if v := r.URL.Query().Get("lead_id"); v != "" {
				parseIntParam(v, &req.LeadId)
			}
			resp, err := client.GetAllCancellations(ctx, &req)
			writeResponse(w, resp, err)
		},
	); err != nil {
		return err
	}

	// GET /v1/meetings/cancellation/{meeting_id}
	if err := mux.HandlePath("GET", "/v1/meetings/cancellation/{meeting_id}",
		func(w http.ResponseWriter, r *http.Request, params map[string]string) {
			var req GetByMeetingIDRequest
			parseIntParam(params["meeting_id"], &req.MeetingId)
			resp, err := client.GetCancellationByID(ctx, &req)
			writeResponse(w, resp, err)
		},
	); err != nil {
		return err
	}

	// PUT /v1/meetings/cancellation/{meeting_id}
	if err := mux.HandlePath("PUT", "/v1/meetings/cancellation/{meeting_id}",
		func(w http.ResponseWriter, r *http.Request, params map[string]string) {
			var req UpdateCancellationRequest
			if err := codec.NewDecoder(r.Body).Decode(&req); err != nil {
				http.Error(w, err.Error(), http.StatusBadRequest)
				return
			}
			parseIntParam(params["meeting_id"], &req.MeetingId)
			resp, err := client.UpdateCancellation(ctx, &req)
			writeResponse(w, resp, err)
		},
	); err != nil {
		return err
	}

	// DELETE /v1/meetings/cancellation/{meeting_id}
	if err := mux.HandlePath("DELETE", "/v1/meetings/cancellation/{meeting_id}",
		func(w http.ResponseWriter, r *http.Request, params map[string]string) {
			var req DeleteByMeetingIDRequest
			parseIntParam(params["meeting_id"], &req.MeetingId)
			resp, err := client.DeleteCancellation(ctx, &req)
			writeResponse(w, resp, err)
		},
	); err != nil {
		return err
	}

	// ---- Success endpoints ---------------------------------------------

	// POST /v1/meetings/success
	if err := mux.HandlePath("POST", "/v1/meetings/success",
		func(w http.ResponseWriter, r *http.Request, _ map[string]string) {
			var req CreateSuccessRequest
			if err := codec.NewDecoder(r.Body).Decode(&req); err != nil {
				http.Error(w, err.Error(), http.StatusBadRequest)
				return
			}
			resp, err := client.CreateSuccess(ctx, &req)
			writeResponse(w, resp, err)
		},
	); err != nil {
		return err
	}

	// GET /v1/meetings/success?lead_id=
	if err := mux.HandlePath("GET", "/v1/meetings/success",
		func(w http.ResponseWriter, r *http.Request, _ map[string]string) {
			var req GetByLeadIDRequest
			if v := r.URL.Query().Get("lead_id"); v != "" {
				parseIntParam(v, &req.LeadId)
			}
			resp, err := client.GetAllSuccesses(ctx, &req)
			writeResponse(w, resp, err)
		},
	); err != nil {
		return err
	}

	// GET /v1/meetings/success/{lead_id}
	if err := mux.HandlePath("GET", "/v1/meetings/success/{lead_id}",
		func(w http.ResponseWriter, r *http.Request, params map[string]string) {
			var req GetByLeadIDRequest
			parseIntParam(params["lead_id"], &req.LeadId)
			resp, err := client.GetSuccessByLeadID(ctx, &req)
			writeResponse(w, resp, err)
		},
	); err != nil {
		return err
	}

	// PUT /v1/meetings/success/{lead_id}
	if err := mux.HandlePath("PUT", "/v1/meetings/success/{lead_id}",
		func(w http.ResponseWriter, r *http.Request, params map[string]string) {
			var req UpdateSuccessRequest
			if err := codec.NewDecoder(r.Body).Decode(&req); err != nil {
				http.Error(w, err.Error(), http.StatusBadRequest)
				return
			}
			parseIntParam(params["lead_id"], &req.LeadId)
			resp, err := client.UpdateSuccess(ctx, &req)
			writeResponse(w, resp, err)
		},
	); err != nil {
		return err
	}

	// DELETE /v1/meetings/success/{lead_id}
	if err := mux.HandlePath("DELETE", "/v1/meetings/success/{lead_id}",
		func(w http.ResponseWriter, r *http.Request, params map[string]string) {
			var req GetByLeadIDRequest
			parseIntParam(params["lead_id"], &req.LeadId)
			resp, err := client.DeleteSuccess(ctx, &req)
			writeResponse(w, resp, err)
		},
	); err != nil {
		return err
	}

	// ---- Scheduled endpoints -------------------------------------------

	// POST /v1/meetings/scheduled
	if err := mux.HandlePath("POST", "/v1/meetings/scheduled",
		func(w http.ResponseWriter, r *http.Request, _ map[string]string) {
			var req CreateScheduledRequest
			if err := codec.NewDecoder(r.Body).Decode(&req); err != nil {
				http.Error(w, err.Error(), http.StatusBadRequest)
				return
			}
			resp, err := client.CreateScheduled(ctx, &req)
			writeResponse(w, resp, err)
		},
	); err != nil {
		return err
	}

	// GET /v1/meetings/scheduled?lead_id=
	if err := mux.HandlePath("GET", "/v1/meetings/scheduled",
		func(w http.ResponseWriter, r *http.Request, _ map[string]string) {
			var req GetScheduledByLeadIDRequest
			parseIntParam(r.URL.Query().Get("lead_id"), &req.LeadId)
			resp, err := client.GetAllScheduled(ctx, &req)
			writeResponse(w, resp, err)
		},
	); err != nil {
		return err
	}

	// GET /v1/meetings/scheduled/{id}
	if err := mux.HandlePath("GET", "/v1/meetings/scheduled/{id}",
		func(w http.ResponseWriter, r *http.Request, params map[string]string) {
			var req GetScheduledByIDRequest
			parseIntParam(params["id"], &req.Id)
			resp, err := client.GetScheduledByID(ctx, &req)
			writeResponse(w, resp, err)
		},
	); err != nil {
		return err
	}

	// PUT /v1/meetings/scheduled/{id}
	if err := mux.HandlePath("PUT", "/v1/meetings/scheduled/{id}",
		func(w http.ResponseWriter, r *http.Request, params map[string]string) {
			var req UpdateScheduledRequest
			if err := codec.NewDecoder(r.Body).Decode(&req); err != nil {
				http.Error(w, err.Error(), http.StatusBadRequest)
				return
			}
			parseIntParam(params["id"], &req.Id)
			resp, err := client.UpdateScheduled(ctx, &req)
			writeResponse(w, resp, err)
		},
	); err != nil {
		return err
	}

	// DELETE /v1/meetings/scheduled/{id}
	if err := mux.HandlePath("DELETE", "/v1/meetings/scheduled/{id}",
		func(w http.ResponseWriter, r *http.Request, params map[string]string) {
			var req DeleteScheduledByIDRequest
			parseIntParam(params["id"], &req.Id)
			resp, err := client.DeleteScheduled(ctx, &req)
			writeResponse(w, resp, err)
		},
	); err != nil {
		return err
	}

	// ---- Rescheduled endpoints -----------------------------------------

	// POST /v1/meetings/rescheduled
	if err := mux.HandlePath("POST", "/v1/meetings/rescheduled",
		func(w http.ResponseWriter, r *http.Request, _ map[string]string) {
			var req CreateRescheduledRequest
			if err := codec.NewDecoder(r.Body).Decode(&req); err != nil {
				http.Error(w, err.Error(), http.StatusBadRequest)
				return
			}
			resp, err := client.CreateRescheduled(ctx, &req)
			writeResponse(w, resp, err)
		},
	); err != nil {
		return err
	}

	// GET /v1/meetings/rescheduled?lead_id=
	if err := mux.HandlePath("GET", "/v1/meetings/rescheduled",
		func(w http.ResponseWriter, r *http.Request, _ map[string]string) {
			var req GetRescheduledByLeadIDRequest
			parseIntParam(r.URL.Query().Get("lead_id"), &req.LeadId)
			resp, err := client.GetAllRescheduled(ctx, &req)
			writeResponse(w, resp, err)
		},
	); err != nil {
		return err
	}

	// GET /v1/meetings/rescheduled/{id}
	if err := mux.HandlePath("GET", "/v1/meetings/rescheduled/{id}",
		func(w http.ResponseWriter, r *http.Request, params map[string]string) {
			var req GetRescheduledByIDRequest
			parseIntParam(params["id"], &req.Id)
			resp, err := client.GetRescheduledByID(ctx, &req)
			writeResponse(w, resp, err)
		},
	); err != nil {
		return err
	}

	// PUT /v1/meetings/rescheduled/{id}
	if err := mux.HandlePath("PUT", "/v1/meetings/rescheduled/{id}",
		func(w http.ResponseWriter, r *http.Request, params map[string]string) {
			var req UpdateRescheduledRequest
			if err := codec.NewDecoder(r.Body).Decode(&req); err != nil {
				http.Error(w, err.Error(), http.StatusBadRequest)
				return
			}
			parseIntParam(params["id"], &req.Id)
			resp, err := client.UpdateRescheduled(ctx, &req)
			writeResponse(w, resp, err)
		},
	); err != nil {
		return err
	}

	// DELETE /v1/meetings/rescheduled/{id}
	if err := mux.HandlePath("DELETE", "/v1/meetings/rescheduled/{id}",
		func(w http.ResponseWriter, r *http.Request, params map[string]string) {
			var req DeleteRescheduledByIDRequest
			parseIntParam(params["id"], &req.Id)
			resp, err := client.DeleteRescheduled(ctx, &req)
			writeResponse(w, resp, err)
		},
	); err != nil {
		return err
	}

	return nil
}
