// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.1
// source: notify.proto

package notify

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	NotifyService_CreateCancellation_FullMethodName  = "/notify.NotifyService/CreateCancellation"
	NotifyService_GetAllCancellations_FullMethodName = "/notify.NotifyService/GetAllCancellations"
	NotifyService_GetCancellationByID_FullMethodName = "/notify.NotifyService/GetCancellationByID"
	NotifyService_CreateSuccess_FullMethodName       = "/notify.NotifyService/CreateSuccess"
	NotifyService_GetAllSuccesses_FullMethodName     = "/notify.NotifyService/GetAllSuccesses"
	NotifyService_GetSuccessByLeadID_FullMethodName  = "/notify.NotifyService/GetSuccessByLeadID"
	NotifyService_CreateScheduled_FullMethodName     = "/notify.NotifyService/CreateScheduled"
	NotifyService_GetAllScheduled_FullMethodName     = "/notify.NotifyService/GetAllScheduled"
	NotifyService_GetScheduledByID_FullMethodName    = "/notify.NotifyService/GetScheduledByID"
	NotifyService_CreateRescheduled_FullMethodName   = "/notify.NotifyService/CreateRescheduled"
	NotifyService_GetAllRescheduled_FullMethodName   = "/notify.NotifyService/GetAllRescheduled"
	NotifyService_GetRescheduledByID_FullMethodName  = "/notify.NotifyService/GetRescheduledByID"
	NotifyService_CreateLead_FullMethodName          = "/notify.NotifyService/CreateLead"
	NotifyService_GetAllLeads_FullMethodName         = "/notify.NotifyService/GetAllLeads"
	NotifyService_GetLeadByID_FullMethodName         = "/notify.NotifyService/GetLeadByID"
	NotifyService_CreateBooking_FullMethodName       = "/notify.NotifyService/CreateBooking"
	NotifyService_GetAllBookings_FullMethodName      = "/notify.NotifyService/GetAllBookings"
	NotifyService_GetBookingByID_FullMethodName      = "/notify.NotifyService/GetBookingByID"
	NotifyService_GetCounts_FullMethodName           = "/notify.NotifyService/GetCounts"
)

// NotifyServiceClient is the client API for NotifyService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type NotifyServiceClient interface {
	// Cancellation
	CreateCancellation(ctx context.Context, in *CreateCancellationRequest, opts ...grpc.CallOption) (*CancellationResponse, error)
	GetAllCancellations(ctx context.Context, in *GetByLeadIDRequest, opts ...grpc.CallOption) (*CancellationListResponse, error)
	GetCancellationByID(ctx context.Context, in *GetByMeetingIDRequest, opts ...grpc.CallOption) (*CancellationResponse, error)
	// Success
	CreateSuccess(ctx context.Context, in *CreateSuccessRequest, opts ...grpc.CallOption) (*SuccessResponse, error)
	GetAllSuccesses(ctx context.Context, in *GetByLeadIDRequest, opts ...grpc.CallOption) (*SuccessListResponse, error)
	GetSuccessByLeadID(ctx context.Context, in *GetByLeadIDRequest, opts ...grpc.CallOption) (*SuccessResponse, error)
	// Scheduled
	CreateScheduled(ctx context.Context, in *CreateScheduledRequest, opts ...grpc.CallOption) (*ScheduledResponse, error)
	GetAllScheduled(ctx context.Context, in *GetScheduledByLeadIDRequest, opts ...grpc.CallOption) (*ScheduledListResponse, error)
	GetScheduledByID(ctx context.Context, in *GetScheduledByIDRequest, opts ...grpc.CallOption) (*ScheduledResponse, error)
	// Rescheduled
	CreateRescheduled(ctx context.Context, in *CreateRescheduledRequest, opts ...grpc.CallOption) (*RescheduledResponse, error)
	GetAllRescheduled(ctx context.Context, in *GetRescheduledByLeadIDRequest, opts ...grpc.CallOption) (*RescheduledListResponse, error)
	GetRescheduledByID(ctx context.Context, in *GetRescheduledByIDRequest, opts ...grpc.CallOption) (*RescheduledResponse, error)
	// Leads
	CreateLead(ctx context.Context, in *CreateLeadRequest, opts ...grpc.CallOption) (*LeadResponse, error)
	GetAllLeads(ctx context.Context, in *CountsRequest, opts ...grpc.CallOption) (*LeadListResponse, error)
	GetLeadByID(ctx context.Context, in *GetByLeadIDRequest, opts ...grpc.CallOption) (*LeadResponse, error)
	// Booking
	CreateBooking(ctx context.Context, in *CreateBookingRequest, opts ...grpc.CallOption) (*BookingResponse, error)
	GetAllBookings(ctx context.Context, in *GetBookingByLeadIDRequest, opts ...grpc.CallOption) (*BookingListResponse, error)
	GetBookingByID(ctx context.Context, in *GetBookingByIDRequest, opts ...grpc.CallOption) (*BookingResponse, error)
	// Counts
	GetCounts(ctx context.Context, in *CountsRequest, opts ...grpc.CallOption) (*CountsResponse, error)
}

type notifyServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewNotifyServiceClient(cc grpc.ClientConnInterface) NotifyServiceClient {
	return &notifyServiceClient{cc}
}

func (c *notifyServiceClient) CreateCancellation(ctx context.Context, in *CreateCancellationRequest, opts ...grpc.CallOption) (*CancellationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CancellationResponse)
	err := c.cc.Invoke(ctx, NotifyService_CreateCancellation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *notifyServiceClient) GetAllCancellations(ctx context.Context, in *GetByLeadIDRequest, opts ...grpc.CallOption) (*CancellationListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CancellationListResponse)
	err := c.cc.Invoke(ctx, NotifyService_GetAllCancellations_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *notifyServiceClient) GetCancellationByID(ctx context.Context, in *GetByMeetingIDRequest, opts ...grpc.CallOption) (*CancellationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CancellationResponse)
	err := c.cc.Invoke(ctx, NotifyService_GetCancellationByID_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *notifyServiceClient) CreateSuccess(ctx context.Context, in *CreateSuccessRequest, opts ...grpc.CallOption) (*SuccessResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SuccessResponse)
	err := c.cc.Invoke(ctx, NotifyService_CreateSuccess_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *notifyServiceClient) GetAllSuccesses(ctx context.Context, in *GetByLeadIDRequest, opts ...grpc.CallOption) (*SuccessListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SuccessListResponse)
	err := c.cc.Invoke(ctx, NotifyService_GetAllSuccesses_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *notifyServiceClient) GetSuccessByLeadID(ctx context.Context, in *GetByLeadIDRequest, opts ...grpc.CallOption) (*SuccessResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SuccessResponse)
	err := c.cc.Invoke(ctx, NotifyService_GetSuccessByLeadID_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *notifyServiceClient) CreateScheduled(ctx context.Context, in *CreateScheduledRequest, opts ...grpc.CallOption) (*ScheduledResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ScheduledResponse)
	err := c.cc.Invoke(ctx, NotifyService_CreateScheduled_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *notifyServiceClient) GetAllScheduled(ctx context.Context, in *GetScheduledByLeadIDRequest, opts ...grpc.CallOption) (*ScheduledListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ScheduledListResponse)
	err := c.cc.Invoke(ctx, NotifyService_GetAllScheduled_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *notifyServiceClient) GetScheduledByID(ctx context.Context, in *GetScheduledByIDRequest, opts ...grpc.CallOption) (*ScheduledResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ScheduledResponse)
	err := c.cc.Invoke(ctx, NotifyService_GetScheduledByID_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *notifyServiceClient) CreateRescheduled(ctx context.Context, in *CreateRescheduledRequest, opts ...grpc.CallOption) (*RescheduledResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RescheduledResponse)
	err := c.cc.Invoke(ctx, NotifyService_CreateRescheduled_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *notifyServiceClient) GetAllRescheduled(ctx context.Context, in *GetRescheduledByLeadIDRequest, opts ...grpc.CallOption) (*RescheduledListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RescheduledListResponse)
	err := c.cc.Invoke(ctx, NotifyService_GetAllRescheduled_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *notifyServiceClient) GetRescheduledByID(ctx context.Context, in *GetRescheduledByIDRequest, opts ...grpc.CallOption) (*RescheduledResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RescheduledResponse)
	err := c.cc.Invoke(ctx, NotifyService_GetRescheduledByID_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *notifyServiceClient) CreateLead(ctx context.Context, in *CreateLeadRequest, opts ...grpc.CallOption) (*LeadResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LeadResponse)
	err := c.cc.Invoke(ctx, NotifyService_CreateLead_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *notifyServiceClient) GetAllLeads(ctx context.Context, in *CountsRequest, opts ...grpc.CallOption) (*LeadListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LeadListResponse)
	err := c.cc.Invoke(ctx, NotifyService_GetAllLeads_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *notifyServiceClient) GetLeadByID(ctx context.Context, in *GetByLeadIDRequest, opts ...grpc.CallOption) (*LeadResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LeadResponse)
	err := c.cc.Invoke(ctx, NotifyService_GetLeadByID_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *notifyServiceClient) CreateBooking(ctx context.Context, in *CreateBookingRequest, opts ...grpc.CallOption) (*BookingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BookingResponse)
	err := c.cc.Invoke(ctx, NotifyService_CreateBooking_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *notifyServiceClient) GetAllBookings(ctx context.Context, in *GetBookingByLeadIDRequest, opts ...grpc.CallOption) (*BookingListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BookingListResponse)
	err := c.cc.Invoke(ctx, NotifyService_GetAllBookings_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *notifyServiceClient) GetBookingByID(ctx context.Context, in *GetBookingByIDRequest, opts ...grpc.CallOption) (*BookingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BookingResponse)
	err := c.cc.Invoke(ctx, NotifyService_GetBookingByID_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *notifyServiceClient) GetCounts(ctx context.Context, in *CountsRequest, opts ...grpc.CallOption) (*CountsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CountsResponse)
	err := c.cc.Invoke(ctx, NotifyService_GetCounts_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NotifyServiceServer is the server API for NotifyService service.
// All implementations must embed UnimplementedNotifyServiceServer
// for forward compatibility.
type NotifyServiceServer interface {
	// Cancellation
	CreateCancellation(context.Context, *CreateCancellationRequest) (*CancellationResponse, error)
	GetAllCancellations(context.Context, *GetByLeadIDRequest) (*CancellationListResponse, error)
	GetCancellationByID(context.Context, *GetByMeetingIDRequest) (*CancellationResponse, error)
	// Success
	CreateSuccess(context.Context, *CreateSuccessRequest) (*SuccessResponse, error)
	GetAllSuccesses(context.Context, *GetByLeadIDRequest) (*SuccessListResponse, error)
	GetSuccessByLeadID(context.Context, *GetByLeadIDRequest) (*SuccessResponse, error)
	// Scheduled
	CreateScheduled(context.Context, *CreateScheduledRequest) (*ScheduledResponse, error)
	GetAllScheduled(context.Context, *GetScheduledByLeadIDRequest) (*ScheduledListResponse, error)
	GetScheduledByID(context.Context, *GetScheduledByIDRequest) (*ScheduledResponse, error)
	// Rescheduled
	CreateRescheduled(context.Context, *CreateRescheduledRequest) (*RescheduledResponse, error)
	GetAllRescheduled(context.Context, *GetRescheduledByLeadIDRequest) (*RescheduledListResponse, error)
	GetRescheduledByID(context.Context, *GetRescheduledByIDRequest) (*RescheduledResponse, error)
	// Leads
	CreateLead(context.Context, *CreateLeadRequest) (*LeadResponse, error)
	GetAllLeads(context.Context, *CountsRequest) (*LeadListResponse, error)
	GetLeadByID(context.Context, *GetByLeadIDRequest) (*LeadResponse, error)
	// Booking
	CreateBooking(context.Context, *CreateBookingRequest) (*BookingResponse, error)
	GetAllBookings(context.Context, *GetBookingByLeadIDRequest) (*BookingListResponse, error)
	GetBookingByID(context.Context, *GetBookingByIDRequest) (*BookingResponse, error)
	// Counts
	GetCounts(context.Context, *CountsRequest) (*CountsResponse, error)
	mustEmbedUnimplementedNotifyServiceServer()
}

// UnimplementedNotifyServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedNotifyServiceServer struct{}

func (UnimplementedNotifyServiceServer) CreateCancellation(context.Context, *CreateCancellationRequest) (*CancellationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateCancellation not implemented")
}
func (UnimplementedNotifyServiceServer) GetAllCancellations(context.Context, *GetByLeadIDRequest) (*CancellationListResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAllCancellations not implemented")
}
func (UnimplementedNotifyServiceServer) GetCancellationByID(context.Context, *GetByMeetingIDRequest) (*CancellationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCancellationByID not implemented")
}
func (UnimplementedNotifyServiceServer) CreateSuccess(context.Context, *CreateSuccessRequest) (*SuccessResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateSuccess not implemented")
}
func (UnimplementedNotifyServiceServer) GetAllSuccesses(context.Context, *GetByLeadIDRequest) (*SuccessListResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAllSuccesses not implemented")
}
func (UnimplementedNotifyServiceServer) GetSuccessByLeadID(context.Context, *GetByLeadIDRequest) (*SuccessResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSuccessByLeadID not implemented")
}
func (UnimplementedNotifyServiceServer) CreateScheduled(context.Context, *CreateScheduledRequest) (*ScheduledResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateScheduled not implemented")
}
func (UnimplementedNotifyServiceServer) GetAllScheduled(context.Context, *GetScheduledByLeadIDRequest) (*ScheduledListResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAllScheduled not implemented")
}
func (UnimplementedNotifyServiceServer) GetScheduledByID(context.Context, *GetScheduledByIDRequest) (*ScheduledResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetScheduledByID not implemented")
}
func (UnimplementedNotifyServiceServer) CreateRescheduled(context.Context, *CreateRescheduledRequest) (*RescheduledResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateRescheduled not implemented")
}
func (UnimplementedNotifyServiceServer) GetAllRescheduled(context.Context, *GetRescheduledByLeadIDRequest) (*RescheduledListResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAllRescheduled not implemented")
}
func (UnimplementedNotifyServiceServer) GetRescheduledByID(context.Context, *GetRescheduledByIDRequest) (*RescheduledResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetRescheduledByID not implemented")
}
func (UnimplementedNotifyServiceServer) CreateLead(context.Context, *CreateLeadRequest) (*LeadResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateLead not implemented")
}
func (UnimplementedNotifyServiceServer) GetAllLeads(context.Context, *CountsRequest) (*LeadListResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAllLeads not implemented")
}
func (UnimplementedNotifyServiceServer) GetLeadByID(context.Context, *GetByLeadIDRequest) (*LeadResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetLeadByID not implemented")
}
func (UnimplementedNotifyServiceServer) CreateBooking(context.Context, *CreateBookingRequest) (*BookingResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateBooking not implemented")
}
func (UnimplementedNotifyServiceServer) GetAllBookings(context.Context, *GetBookingByLeadIDRequest) (*BookingListResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAllBookings not implemented")
}
func (UnimplementedNotifyServiceServer) GetBookingByID(context.Context, *GetBookingByIDRequest) (*BookingResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetBookingByID not implemented")
}
func (UnimplementedNotifyServiceServer) GetCounts(context.Context, *CountsRequest) (*CountsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCounts not implemented")
}
func (UnimplementedNotifyServiceServer) mustEmbedUnimplementedNotifyServiceServer() {}
func (UnimplementedNotifyServiceServer) testEmbeddedByValue()                       {}

// UnsafeNotifyServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NotifyServiceServer will
// result in compilation errors.
type UnsafeNotifyServiceServer interface {
	mustEmbedUnimplementedNotifyServiceServer()
}

func RegisterNotifyServiceServer(s grpc.ServiceRegistrar, srv NotifyServiceServer) {
	// If the following call panics, it indicates UnimplementedNotifyServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&NotifyService_ServiceDesc, srv)
}

func _NotifyService_CreateCancellation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateCancellationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotifyServiceServer).CreateCancellation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NotifyService_CreateCancellation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotifyServiceServer).CreateCancellation(ctx, req.(*CreateCancellationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NotifyService_GetAllCancellations_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetByLeadIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotifyServiceServer).GetAllCancellations(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NotifyService_GetAllCancellations_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotifyServiceServer).GetAllCancellations(ctx, req.(*GetByLeadIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NotifyService_GetCancellationByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetByMeetingIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotifyServiceServer).GetCancellationByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NotifyService_GetCancellationByID_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotifyServiceServer).GetCancellationByID(ctx, req.(*GetByMeetingIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NotifyService_CreateSuccess_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateSuccessRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotifyServiceServer).CreateSuccess(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NotifyService_CreateSuccess_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotifyServiceServer).CreateSuccess(ctx, req.(*CreateSuccessRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NotifyService_GetAllSuccesses_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetByLeadIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotifyServiceServer).GetAllSuccesses(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NotifyService_GetAllSuccesses_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotifyServiceServer).GetAllSuccesses(ctx, req.(*GetByLeadIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NotifyService_GetSuccessByLeadID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetByLeadIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotifyServiceServer).GetSuccessByLeadID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NotifyService_GetSuccessByLeadID_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotifyServiceServer).GetSuccessByLeadID(ctx, req.(*GetByLeadIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NotifyService_CreateScheduled_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateScheduledRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotifyServiceServer).CreateScheduled(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NotifyService_CreateScheduled_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotifyServiceServer).CreateScheduled(ctx, req.(*CreateScheduledRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NotifyService_GetAllScheduled_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetScheduledByLeadIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotifyServiceServer).GetAllScheduled(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NotifyService_GetAllScheduled_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotifyServiceServer).GetAllScheduled(ctx, req.(*GetScheduledByLeadIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NotifyService_GetScheduledByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetScheduledByIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotifyServiceServer).GetScheduledByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NotifyService_GetScheduledByID_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotifyServiceServer).GetScheduledByID(ctx, req.(*GetScheduledByIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NotifyService_CreateRescheduled_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateRescheduledRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotifyServiceServer).CreateRescheduled(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NotifyService_CreateRescheduled_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotifyServiceServer).CreateRescheduled(ctx, req.(*CreateRescheduledRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NotifyService_GetAllRescheduled_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRescheduledByLeadIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotifyServiceServer).GetAllRescheduled(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NotifyService_GetAllRescheduled_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotifyServiceServer).GetAllRescheduled(ctx, req.(*GetRescheduledByLeadIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NotifyService_GetRescheduledByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRescheduledByIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotifyServiceServer).GetRescheduledByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NotifyService_GetRescheduledByID_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotifyServiceServer).GetRescheduledByID(ctx, req.(*GetRescheduledByIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NotifyService_CreateLead_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateLeadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotifyServiceServer).CreateLead(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NotifyService_CreateLead_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotifyServiceServer).CreateLead(ctx, req.(*CreateLeadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NotifyService_GetAllLeads_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CountsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotifyServiceServer).GetAllLeads(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NotifyService_GetAllLeads_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotifyServiceServer).GetAllLeads(ctx, req.(*CountsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NotifyService_GetLeadByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetByLeadIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotifyServiceServer).GetLeadByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NotifyService_GetLeadByID_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotifyServiceServer).GetLeadByID(ctx, req.(*GetByLeadIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NotifyService_CreateBooking_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateBookingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotifyServiceServer).CreateBooking(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NotifyService_CreateBooking_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotifyServiceServer).CreateBooking(ctx, req.(*CreateBookingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NotifyService_GetAllBookings_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBookingByLeadIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotifyServiceServer).GetAllBookings(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NotifyService_GetAllBookings_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotifyServiceServer).GetAllBookings(ctx, req.(*GetBookingByLeadIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NotifyService_GetBookingByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBookingByIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotifyServiceServer).GetBookingByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NotifyService_GetBookingByID_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotifyServiceServer).GetBookingByID(ctx, req.(*GetBookingByIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NotifyService_GetCounts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CountsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotifyServiceServer).GetCounts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NotifyService_GetCounts_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotifyServiceServer).GetCounts(ctx, req.(*CountsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// NotifyService_ServiceDesc is the grpc.ServiceDesc for NotifyService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var NotifyService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "notify.NotifyService",
	HandlerType: (*NotifyServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateCancellation",
			Handler:    _NotifyService_CreateCancellation_Handler,
		},
		{
			MethodName: "GetAllCancellations",
			Handler:    _NotifyService_GetAllCancellations_Handler,
		},
		{
			MethodName: "GetCancellationByID",
			Handler:    _NotifyService_GetCancellationByID_Handler,
		},
		{
			MethodName: "CreateSuccess",
			Handler:    _NotifyService_CreateSuccess_Handler,
		},
		{
			MethodName: "GetAllSuccesses",
			Handler:    _NotifyService_GetAllSuccesses_Handler,
		},
		{
			MethodName: "GetSuccessByLeadID",
			Handler:    _NotifyService_GetSuccessByLeadID_Handler,
		},
		{
			MethodName: "CreateScheduled",
			Handler:    _NotifyService_CreateScheduled_Handler,
		},
		{
			MethodName: "GetAllScheduled",
			Handler:    _NotifyService_GetAllScheduled_Handler,
		},
		{
			MethodName: "GetScheduledByID",
			Handler:    _NotifyService_GetScheduledByID_Handler,
		},
		{
			MethodName: "CreateRescheduled",
			Handler:    _NotifyService_CreateRescheduled_Handler,
		},
		{
			MethodName: "GetAllRescheduled",
			Handler:    _NotifyService_GetAllRescheduled_Handler,
		},
		{
			MethodName: "GetRescheduledByID",
			Handler:    _NotifyService_GetRescheduledByID_Handler,
		},
		{
			MethodName: "CreateLead",
			Handler:    _NotifyService_CreateLead_Handler,
		},
		{
			MethodName: "GetAllLeads",
			Handler:    _NotifyService_GetAllLeads_Handler,
		},
		{
			MethodName: "GetLeadByID",
			Handler:    _NotifyService_GetLeadByID_Handler,
		},
		{
			MethodName: "CreateBooking",
			Handler:    _NotifyService_CreateBooking_Handler,
		},
		{
			MethodName: "GetAllBookings",
			Handler:    _NotifyService_GetAllBookings_Handler,
		},
		{
			MethodName: "GetBookingByID",
			Handler:    _NotifyService_GetBookingByID_Handler,
		},
		{
			MethodName: "GetCounts",
			Handler:    _NotifyService_GetCounts_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "notify.proto",
}
