  mysql_details:
    username: "root"
    password: "Root@123"
    address: "127.0.0.1"
    port: "3306"
    db_name: "notify_db"

  grpc_details:
    network: "tcp"
    address: ":50051"
    endpoint: "localhost:50051"

  http_details:
    port: ":8080"