// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.1
// source: design.proto

package design

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DesignService_CreateDesignLeadPre10_FullMethodName          = "/design.DesignService/CreateDesignLeadPre10"
	DesignService_CreateDesignLead1020_FullMethodName           = "/design.DesignService/CreateDesignLead1020"
	DesignService_CreateDesignMilestone_FullMethodName          = "/design.DesignService/CreateDesignMilestone"
	DesignService_CreateDesignPaymentRequest_FullMethodName     = "/design.DesignService/CreateDesignPaymentRequest"
	DesignService_CreateDesignPaymentStatus_FullMethodName      = "/design.DesignService/CreateDesignPaymentStatus"
	DesignService_CreateDesignDQCRequest_FullMethodName         = "/design.DesignService/CreateDesignDQCRequest"
	DesignService_CreateDesignDQCStatus_FullMethodName          = "/design.DesignService/CreateDesignDQCStatus"
	DesignService_CreateDesignMMTRequest_FullMethodName         = "/design.DesignService/CreateDesignMMTRequest"
	DesignService_CreateDesignMMTAssign_FullMethodName          = "/design.DesignService/CreateDesignMMTAssign"
	DesignService_CreateDesignMMTDocReady_FullMethodName        = "/design.DesignService/CreateDesignMMTDocReady"
	DesignService_CreateDesignMeeting_FullMethodName            = "/design.DesignService/CreateDesignMeeting"
	DesignService_CreateDesignAssignDesigner_FullMethodName     = "/design.DesignService/CreateDesignAssignDesigner"
	DesignService_CreateDesignAssignPM_FullMethodName           = "/design.DesignService/CreateDesignAssignPM"
	DesignService_CreateDesignQuote_FullMethodName              = "/design.DesignService/CreateDesignQuote"
	DesignService_CreateDesignP2P_FullMethodName                = "/design.DesignService/CreateDesignP2P"
	DesignService_CreateDesignPMStatus_FullMethodName           = "/design.DesignService/CreateDesignPMStatus"
	DesignService_GetDesignNotificationFeed_FullMethodName      = "/design.DesignService/GetDesignNotificationFeed"
	DesignService_GetDesignNotificationDetails_FullMethodName   = "/design.DesignService/GetDesignNotificationDetails"
	DesignService_GetDesignNotificationCounts_FullMethodName    = "/design.DesignService/GetDesignNotificationCounts"
	DesignService_GetDesignInbox_FullMethodName                 = "/design.DesignService/GetDesignInbox"
	DesignService_GetDesignInboxCounts_FullMethodName           = "/design.DesignService/GetDesignInboxCounts"
	DesignService_MarkDesignNotificationRead_FullMethodName     = "/design.DesignService/MarkDesignNotificationRead"
	DesignService_MarkAllDesignNotificationsRead_FullMethodName = "/design.DesignService/MarkAllDesignNotificationsRead"
	DesignService_CreateDesignInboxTicket_FullMethodName        = "/design.DesignService/CreateDesignInboxTicket"
)

// DesignServiceClient is the client API for DesignService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DesignServiceClient interface {
	// 01 — Pre-10% New Lead
	CreateDesignLeadPre10(ctx context.Context, in *DesignLeadPre10Request, opts ...grpc.CallOption) (*DesignLeadPre10Response, error)
	// 02 — 10–20% Phase Entered
	CreateDesignLead1020(ctx context.Context, in *DesignLead1020Request, opts ...grpc.CallOption) (*DesignLead1020Response, error)
	// 03 — Milestone Completed
	CreateDesignMilestone(ctx context.Context, in *DesignMilestoneRequest, opts ...grpc.CallOption) (*DesignMilestoneResponse, error)
	// 04 — Payment Requested
	CreateDesignPaymentRequest(ctx context.Context, in *DesignPaymentRequestRequest, opts ...grpc.CallOption) (*DesignPaymentRequestResponse, error)
	// 05 — Payment / Sales Closure Status
	CreateDesignPaymentStatus(ctx context.Context, in *DesignPaymentStatusRequest, opts ...grpc.CallOption) (*DesignPaymentStatusResponse, error)
	// 06 — DQC Requested
	CreateDesignDQCRequest(ctx context.Context, in *DesignDQCRequestRequest, opts ...grpc.CallOption) (*DesignDQCRequestResponse, error)
	// 07 — DQC Status
	CreateDesignDQCStatus(ctx context.Context, in *DesignDQCStatusRequest, opts ...grpc.CallOption) (*DesignDQCStatusResponse, error)
	// 08 — MMT Visit Requested
	CreateDesignMMTRequest(ctx context.Context, in *DesignMMTRequestRequest, opts ...grpc.CallOption) (*DesignMMTRequestResponse, error)
	// 09 — MMT Executive Assigned
	CreateDesignMMTAssign(ctx context.Context, in *DesignMMTAssignRequest, opts ...grpc.CallOption) (*DesignMMTAssignResponse, error)
	// 10 — MMT Documents Ready
	CreateDesignMMTDocReady(ctx context.Context, in *DesignMMTDocReadyRequest, opts ...grpc.CallOption) (*DesignMMTDocReadyResponse, error)
	// 11 — Design Meeting Scheduled
	CreateDesignMeeting(ctx context.Context, in *DesignMeetingRequest, opts ...grpc.CallOption) (*DesignMeetingResponse, error)
	// 12 — Designer Reassignment
	CreateDesignAssignDesigner(ctx context.Context, in *DesignAssignDesignerRequest, opts ...grpc.CallOption) (*DesignAssignDesignerResponse, error)
	// 13 — PM Assignment
	CreateDesignAssignPM(ctx context.Context, in *DesignAssignPMRequest, opts ...grpc.CallOption) (*DesignAssignPMResponse, error)
	// 14 — New Quote
	CreateDesignQuote(ctx context.Context, in *DesignQuoteRequest, opts ...grpc.CallOption) (*DesignQuoteResponse, error)
	// 15 — P2P Completed
	CreateDesignP2P(ctx context.Context, in *DesignP2PRequest, opts ...grpc.CallOption) (*DesignP2PResponse, error)
	// 16 — PM Approve / Reject (after DQC2)
	CreateDesignPMStatus(ctx context.Context, in *DesignPMStatusRequest, opts ...grpc.CallOption) (*DesignPMStatusResponse, error)
	// 17 — Legacy Notification Feed (stubs)
	GetDesignNotificationFeed(ctx context.Context, in *DesignNotificationFeedRequest, opts ...grpc.CallOption) (*DesignNotificationFeedResponse, error)
	// 18 — Legacy Details
	GetDesignNotificationDetails(ctx context.Context, in *DesignNotificationDetailsRequest, opts ...grpc.CallOption) (*DesignNotificationDetailsResponse, error)
	// 18b — Legacy Counts
	GetDesignNotificationCounts(ctx context.Context, in *DesignNotificationCountsRequest, opts ...grpc.CallOption) (*DesignNotificationCountsResponse, error)
	// 19 — Get User Inbox Feed
	GetDesignInbox(ctx context.Context, in *DesignInboxRequest, opts ...grpc.CallOption) (*DesignInboxResponse, error)
	// 20 — Get Unread Counts for Bell Icon
	GetDesignInboxCounts(ctx context.Context, in *DesignInboxCountsRequest, opts ...grpc.CallOption) (*DesignInboxCountsResponse, error)
	// 21 — Mark Single Notification as Read
	MarkDesignNotificationRead(ctx context.Context, in *MarkDesignNotificationReadRequest, opts ...grpc.CallOption) (*MarkDesignNotificationReadResponse, error)
	// 22 — Mark All Notifications as Read
	MarkAllDesignNotificationsRead(ctx context.Context, in *MarkAllDesignNotificationsReadRequest, opts ...grpc.CallOption) (*MarkAllDesignNotificationsReadResponse, error)
	// 23 — Issue WebSocket Handshake Ticket
	CreateDesignInboxTicket(ctx context.Context, in *CreateDesignInboxTicketRequest, opts ...grpc.CallOption) (*CreateDesignInboxTicketResponse, error)
}

type designServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDesignServiceClient(cc grpc.ClientConnInterface) DesignServiceClient {
	return &designServiceClient{cc}
}

func (c *designServiceClient) CreateDesignLeadPre10(ctx context.Context, in *DesignLeadPre10Request, opts ...grpc.CallOption) (*DesignLeadPre10Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DesignLeadPre10Response)
	err := c.cc.Invoke(ctx, DesignService_CreateDesignLeadPre10_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *designServiceClient) CreateDesignLead1020(ctx context.Context, in *DesignLead1020Request, opts ...grpc.CallOption) (*DesignLead1020Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DesignLead1020Response)
	err := c.cc.Invoke(ctx, DesignService_CreateDesignLead1020_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *designServiceClient) CreateDesignMilestone(ctx context.Context, in *DesignMilestoneRequest, opts ...grpc.CallOption) (*DesignMilestoneResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DesignMilestoneResponse)
	err := c.cc.Invoke(ctx, DesignService_CreateDesignMilestone_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *designServiceClient) CreateDesignPaymentRequest(ctx context.Context, in *DesignPaymentRequestRequest, opts ...grpc.CallOption) (*DesignPaymentRequestResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DesignPaymentRequestResponse)
	err := c.cc.Invoke(ctx, DesignService_CreateDesignPaymentRequest_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *designServiceClient) CreateDesignPaymentStatus(ctx context.Context, in *DesignPaymentStatusRequest, opts ...grpc.CallOption) (*DesignPaymentStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DesignPaymentStatusResponse)
	err := c.cc.Invoke(ctx, DesignService_CreateDesignPaymentStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *designServiceClient) CreateDesignDQCRequest(ctx context.Context, in *DesignDQCRequestRequest, opts ...grpc.CallOption) (*DesignDQCRequestResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DesignDQCRequestResponse)
	err := c.cc.Invoke(ctx, DesignService_CreateDesignDQCRequest_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *designServiceClient) CreateDesignDQCStatus(ctx context.Context, in *DesignDQCStatusRequest, opts ...grpc.CallOption) (*DesignDQCStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DesignDQCStatusResponse)
	err := c.cc.Invoke(ctx, DesignService_CreateDesignDQCStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *designServiceClient) CreateDesignMMTRequest(ctx context.Context, in *DesignMMTRequestRequest, opts ...grpc.CallOption) (*DesignMMTRequestResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DesignMMTRequestResponse)
	err := c.cc.Invoke(ctx, DesignService_CreateDesignMMTRequest_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *designServiceClient) CreateDesignMMTAssign(ctx context.Context, in *DesignMMTAssignRequest, opts ...grpc.CallOption) (*DesignMMTAssignResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DesignMMTAssignResponse)
	err := c.cc.Invoke(ctx, DesignService_CreateDesignMMTAssign_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *designServiceClient) CreateDesignMMTDocReady(ctx context.Context, in *DesignMMTDocReadyRequest, opts ...grpc.CallOption) (*DesignMMTDocReadyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DesignMMTDocReadyResponse)
	err := c.cc.Invoke(ctx, DesignService_CreateDesignMMTDocReady_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *designServiceClient) CreateDesignMeeting(ctx context.Context, in *DesignMeetingRequest, opts ...grpc.CallOption) (*DesignMeetingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DesignMeetingResponse)
	err := c.cc.Invoke(ctx, DesignService_CreateDesignMeeting_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *designServiceClient) CreateDesignAssignDesigner(ctx context.Context, in *DesignAssignDesignerRequest, opts ...grpc.CallOption) (*DesignAssignDesignerResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DesignAssignDesignerResponse)
	err := c.cc.Invoke(ctx, DesignService_CreateDesignAssignDesigner_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *designServiceClient) CreateDesignAssignPM(ctx context.Context, in *DesignAssignPMRequest, opts ...grpc.CallOption) (*DesignAssignPMResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DesignAssignPMResponse)
	err := c.cc.Invoke(ctx, DesignService_CreateDesignAssignPM_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *designServiceClient) CreateDesignQuote(ctx context.Context, in *DesignQuoteRequest, opts ...grpc.CallOption) (*DesignQuoteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DesignQuoteResponse)
	err := c.cc.Invoke(ctx, DesignService_CreateDesignQuote_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *designServiceClient) CreateDesignP2P(ctx context.Context, in *DesignP2PRequest, opts ...grpc.CallOption) (*DesignP2PResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DesignP2PResponse)
	err := c.cc.Invoke(ctx, DesignService_CreateDesignP2P_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *designServiceClient) CreateDesignPMStatus(ctx context.Context, in *DesignPMStatusRequest, opts ...grpc.CallOption) (*DesignPMStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DesignPMStatusResponse)
	err := c.cc.Invoke(ctx, DesignService_CreateDesignPMStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *designServiceClient) GetDesignNotificationFeed(ctx context.Context, in *DesignNotificationFeedRequest, opts ...grpc.CallOption) (*DesignNotificationFeedResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DesignNotificationFeedResponse)
	err := c.cc.Invoke(ctx, DesignService_GetDesignNotificationFeed_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *designServiceClient) GetDesignNotificationDetails(ctx context.Context, in *DesignNotificationDetailsRequest, opts ...grpc.CallOption) (*DesignNotificationDetailsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DesignNotificationDetailsResponse)
	err := c.cc.Invoke(ctx, DesignService_GetDesignNotificationDetails_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *designServiceClient) GetDesignNotificationCounts(ctx context.Context, in *DesignNotificationCountsRequest, opts ...grpc.CallOption) (*DesignNotificationCountsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DesignNotificationCountsResponse)
	err := c.cc.Invoke(ctx, DesignService_GetDesignNotificationCounts_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *designServiceClient) GetDesignInbox(ctx context.Context, in *DesignInboxRequest, opts ...grpc.CallOption) (*DesignInboxResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DesignInboxResponse)
	err := c.cc.Invoke(ctx, DesignService_GetDesignInbox_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *designServiceClient) GetDesignInboxCounts(ctx context.Context, in *DesignInboxCountsRequest, opts ...grpc.CallOption) (*DesignInboxCountsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DesignInboxCountsResponse)
	err := c.cc.Invoke(ctx, DesignService_GetDesignInboxCounts_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *designServiceClient) MarkDesignNotificationRead(ctx context.Context, in *MarkDesignNotificationReadRequest, opts ...grpc.CallOption) (*MarkDesignNotificationReadResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MarkDesignNotificationReadResponse)
	err := c.cc.Invoke(ctx, DesignService_MarkDesignNotificationRead_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *designServiceClient) MarkAllDesignNotificationsRead(ctx context.Context, in *MarkAllDesignNotificationsReadRequest, opts ...grpc.CallOption) (*MarkAllDesignNotificationsReadResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MarkAllDesignNotificationsReadResponse)
	err := c.cc.Invoke(ctx, DesignService_MarkAllDesignNotificationsRead_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *designServiceClient) CreateDesignInboxTicket(ctx context.Context, in *CreateDesignInboxTicketRequest, opts ...grpc.CallOption) (*CreateDesignInboxTicketResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateDesignInboxTicketResponse)
	err := c.cc.Invoke(ctx, DesignService_CreateDesignInboxTicket_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DesignServiceServer is the server API for DesignService service.
// All implementations must embed UnimplementedDesignServiceServer
// for forward compatibility.
type DesignServiceServer interface {
	// 01 — Pre-10% New Lead
	CreateDesignLeadPre10(context.Context, *DesignLeadPre10Request) (*DesignLeadPre10Response, error)
	// 02 — 10–20% Phase Entered
	CreateDesignLead1020(context.Context, *DesignLead1020Request) (*DesignLead1020Response, error)
	// 03 — Milestone Completed
	CreateDesignMilestone(context.Context, *DesignMilestoneRequest) (*DesignMilestoneResponse, error)
	// 04 — Payment Requested
	CreateDesignPaymentRequest(context.Context, *DesignPaymentRequestRequest) (*DesignPaymentRequestResponse, error)
	// 05 — Payment / Sales Closure Status
	CreateDesignPaymentStatus(context.Context, *DesignPaymentStatusRequest) (*DesignPaymentStatusResponse, error)
	// 06 — DQC Requested
	CreateDesignDQCRequest(context.Context, *DesignDQCRequestRequest) (*DesignDQCRequestResponse, error)
	// 07 — DQC Status
	CreateDesignDQCStatus(context.Context, *DesignDQCStatusRequest) (*DesignDQCStatusResponse, error)
	// 08 — MMT Visit Requested
	CreateDesignMMTRequest(context.Context, *DesignMMTRequestRequest) (*DesignMMTRequestResponse, error)
	// 09 — MMT Executive Assigned
	CreateDesignMMTAssign(context.Context, *DesignMMTAssignRequest) (*DesignMMTAssignResponse, error)
	// 10 — MMT Documents Ready
	CreateDesignMMTDocReady(context.Context, *DesignMMTDocReadyRequest) (*DesignMMTDocReadyResponse, error)
	// 11 — Design Meeting Scheduled
	CreateDesignMeeting(context.Context, *DesignMeetingRequest) (*DesignMeetingResponse, error)
	// 12 — Designer Reassignment
	CreateDesignAssignDesigner(context.Context, *DesignAssignDesignerRequest) (*DesignAssignDesignerResponse, error)
	// 13 — PM Assignment
	CreateDesignAssignPM(context.Context, *DesignAssignPMRequest) (*DesignAssignPMResponse, error)
	// 14 — New Quote
	CreateDesignQuote(context.Context, *DesignQuoteRequest) (*DesignQuoteResponse, error)
	// 15 — P2P Completed
	CreateDesignP2P(context.Context, *DesignP2PRequest) (*DesignP2PResponse, error)
	// 16 — PM Approve / Reject (after DQC2)
	CreateDesignPMStatus(context.Context, *DesignPMStatusRequest) (*DesignPMStatusResponse, error)
	// 17 — Legacy Notification Feed (stubs)
	GetDesignNotificationFeed(context.Context, *DesignNotificationFeedRequest) (*DesignNotificationFeedResponse, error)
	// 18 — Legacy Details
	GetDesignNotificationDetails(context.Context, *DesignNotificationDetailsRequest) (*DesignNotificationDetailsResponse, error)
	// 18b — Legacy Counts
	GetDesignNotificationCounts(context.Context, *DesignNotificationCountsRequest) (*DesignNotificationCountsResponse, error)
	// 19 — Get User Inbox Feed
	GetDesignInbox(context.Context, *DesignInboxRequest) (*DesignInboxResponse, error)
	// 20 — Get Unread Counts for Bell Icon
	GetDesignInboxCounts(context.Context, *DesignInboxCountsRequest) (*DesignInboxCountsResponse, error)
	// 21 — Mark Single Notification as Read
	MarkDesignNotificationRead(context.Context, *MarkDesignNotificationReadRequest) (*MarkDesignNotificationReadResponse, error)
	// 22 — Mark All Notifications as Read
	MarkAllDesignNotificationsRead(context.Context, *MarkAllDesignNotificationsReadRequest) (*MarkAllDesignNotificationsReadResponse, error)
	// 23 — Issue WebSocket Handshake Ticket
	CreateDesignInboxTicket(context.Context, *CreateDesignInboxTicketRequest) (*CreateDesignInboxTicketResponse, error)
	mustEmbedUnimplementedDesignServiceServer()
}

// UnimplementedDesignServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDesignServiceServer struct{}

func (UnimplementedDesignServiceServer) CreateDesignLeadPre10(context.Context, *DesignLeadPre10Request) (*DesignLeadPre10Response, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateDesignLeadPre10 not implemented")
}
func (UnimplementedDesignServiceServer) CreateDesignLead1020(context.Context, *DesignLead1020Request) (*DesignLead1020Response, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateDesignLead1020 not implemented")
}
func (UnimplementedDesignServiceServer) CreateDesignMilestone(context.Context, *DesignMilestoneRequest) (*DesignMilestoneResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateDesignMilestone not implemented")
}
func (UnimplementedDesignServiceServer) CreateDesignPaymentRequest(context.Context, *DesignPaymentRequestRequest) (*DesignPaymentRequestResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateDesignPaymentRequest not implemented")
}
func (UnimplementedDesignServiceServer) CreateDesignPaymentStatus(context.Context, *DesignPaymentStatusRequest) (*DesignPaymentStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateDesignPaymentStatus not implemented")
}
func (UnimplementedDesignServiceServer) CreateDesignDQCRequest(context.Context, *DesignDQCRequestRequest) (*DesignDQCRequestResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateDesignDQCRequest not implemented")
}
func (UnimplementedDesignServiceServer) CreateDesignDQCStatus(context.Context, *DesignDQCStatusRequest) (*DesignDQCStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateDesignDQCStatus not implemented")
}
func (UnimplementedDesignServiceServer) CreateDesignMMTRequest(context.Context, *DesignMMTRequestRequest) (*DesignMMTRequestResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateDesignMMTRequest not implemented")
}
func (UnimplementedDesignServiceServer) CreateDesignMMTAssign(context.Context, *DesignMMTAssignRequest) (*DesignMMTAssignResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateDesignMMTAssign not implemented")
}
func (UnimplementedDesignServiceServer) CreateDesignMMTDocReady(context.Context, *DesignMMTDocReadyRequest) (*DesignMMTDocReadyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateDesignMMTDocReady not implemented")
}
func (UnimplementedDesignServiceServer) CreateDesignMeeting(context.Context, *DesignMeetingRequest) (*DesignMeetingResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateDesignMeeting not implemented")
}
func (UnimplementedDesignServiceServer) CreateDesignAssignDesigner(context.Context, *DesignAssignDesignerRequest) (*DesignAssignDesignerResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateDesignAssignDesigner not implemented")
}
func (UnimplementedDesignServiceServer) CreateDesignAssignPM(context.Context, *DesignAssignPMRequest) (*DesignAssignPMResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateDesignAssignPM not implemented")
}
func (UnimplementedDesignServiceServer) CreateDesignQuote(context.Context, *DesignQuoteRequest) (*DesignQuoteResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateDesignQuote not implemented")
}
func (UnimplementedDesignServiceServer) CreateDesignP2P(context.Context, *DesignP2PRequest) (*DesignP2PResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateDesignP2P not implemented")
}
func (UnimplementedDesignServiceServer) CreateDesignPMStatus(context.Context, *DesignPMStatusRequest) (*DesignPMStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateDesignPMStatus not implemented")
}
func (UnimplementedDesignServiceServer) GetDesignNotificationFeed(context.Context, *DesignNotificationFeedRequest) (*DesignNotificationFeedResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetDesignNotificationFeed not implemented")
}
func (UnimplementedDesignServiceServer) GetDesignNotificationDetails(context.Context, *DesignNotificationDetailsRequest) (*DesignNotificationDetailsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetDesignNotificationDetails not implemented")
}
func (UnimplementedDesignServiceServer) GetDesignNotificationCounts(context.Context, *DesignNotificationCountsRequest) (*DesignNotificationCountsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetDesignNotificationCounts not implemented")
}
func (UnimplementedDesignServiceServer) GetDesignInbox(context.Context, *DesignInboxRequest) (*DesignInboxResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetDesignInbox not implemented")
}
func (UnimplementedDesignServiceServer) GetDesignInboxCounts(context.Context, *DesignInboxCountsRequest) (*DesignInboxCountsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetDesignInboxCounts not implemented")
}
func (UnimplementedDesignServiceServer) MarkDesignNotificationRead(context.Context, *MarkDesignNotificationReadRequest) (*MarkDesignNotificationReadResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method MarkDesignNotificationRead not implemented")
}
func (UnimplementedDesignServiceServer) MarkAllDesignNotificationsRead(context.Context, *MarkAllDesignNotificationsReadRequest) (*MarkAllDesignNotificationsReadResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method MarkAllDesignNotificationsRead not implemented")
}
func (UnimplementedDesignServiceServer) CreateDesignInboxTicket(context.Context, *CreateDesignInboxTicketRequest) (*CreateDesignInboxTicketResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateDesignInboxTicket not implemented")
}
func (UnimplementedDesignServiceServer) mustEmbedUnimplementedDesignServiceServer() {}
func (UnimplementedDesignServiceServer) testEmbeddedByValue()                       {}

// UnsafeDesignServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DesignServiceServer will
// result in compilation errors.
type UnsafeDesignServiceServer interface {
	mustEmbedUnimplementedDesignServiceServer()
}

func RegisterDesignServiceServer(s grpc.ServiceRegistrar, srv DesignServiceServer) {
	// If the following call panics, it indicates UnimplementedDesignServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DesignService_ServiceDesc, srv)
}

func _DesignService_CreateDesignLeadPre10_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DesignLeadPre10Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DesignServiceServer).CreateDesignLeadPre10(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DesignService_CreateDesignLeadPre10_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DesignServiceServer).CreateDesignLeadPre10(ctx, req.(*DesignLeadPre10Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _DesignService_CreateDesignLead1020_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DesignLead1020Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DesignServiceServer).CreateDesignLead1020(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DesignService_CreateDesignLead1020_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DesignServiceServer).CreateDesignLead1020(ctx, req.(*DesignLead1020Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _DesignService_CreateDesignMilestone_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DesignMilestoneRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DesignServiceServer).CreateDesignMilestone(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DesignService_CreateDesignMilestone_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DesignServiceServer).CreateDesignMilestone(ctx, req.(*DesignMilestoneRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DesignService_CreateDesignPaymentRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DesignPaymentRequestRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DesignServiceServer).CreateDesignPaymentRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DesignService_CreateDesignPaymentRequest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DesignServiceServer).CreateDesignPaymentRequest(ctx, req.(*DesignPaymentRequestRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DesignService_CreateDesignPaymentStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DesignPaymentStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DesignServiceServer).CreateDesignPaymentStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DesignService_CreateDesignPaymentStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DesignServiceServer).CreateDesignPaymentStatus(ctx, req.(*DesignPaymentStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DesignService_CreateDesignDQCRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DesignDQCRequestRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DesignServiceServer).CreateDesignDQCRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DesignService_CreateDesignDQCRequest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DesignServiceServer).CreateDesignDQCRequest(ctx, req.(*DesignDQCRequestRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DesignService_CreateDesignDQCStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DesignDQCStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DesignServiceServer).CreateDesignDQCStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DesignService_CreateDesignDQCStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DesignServiceServer).CreateDesignDQCStatus(ctx, req.(*DesignDQCStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DesignService_CreateDesignMMTRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DesignMMTRequestRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DesignServiceServer).CreateDesignMMTRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DesignService_CreateDesignMMTRequest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DesignServiceServer).CreateDesignMMTRequest(ctx, req.(*DesignMMTRequestRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DesignService_CreateDesignMMTAssign_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DesignMMTAssignRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DesignServiceServer).CreateDesignMMTAssign(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DesignService_CreateDesignMMTAssign_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DesignServiceServer).CreateDesignMMTAssign(ctx, req.(*DesignMMTAssignRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DesignService_CreateDesignMMTDocReady_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DesignMMTDocReadyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DesignServiceServer).CreateDesignMMTDocReady(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DesignService_CreateDesignMMTDocReady_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DesignServiceServer).CreateDesignMMTDocReady(ctx, req.(*DesignMMTDocReadyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DesignService_CreateDesignMeeting_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DesignMeetingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DesignServiceServer).CreateDesignMeeting(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DesignService_CreateDesignMeeting_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DesignServiceServer).CreateDesignMeeting(ctx, req.(*DesignMeetingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DesignService_CreateDesignAssignDesigner_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DesignAssignDesignerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DesignServiceServer).CreateDesignAssignDesigner(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DesignService_CreateDesignAssignDesigner_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DesignServiceServer).CreateDesignAssignDesigner(ctx, req.(*DesignAssignDesignerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DesignService_CreateDesignAssignPM_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DesignAssignPMRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DesignServiceServer).CreateDesignAssignPM(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DesignService_CreateDesignAssignPM_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DesignServiceServer).CreateDesignAssignPM(ctx, req.(*DesignAssignPMRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DesignService_CreateDesignQuote_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DesignQuoteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DesignServiceServer).CreateDesignQuote(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DesignService_CreateDesignQuote_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DesignServiceServer).CreateDesignQuote(ctx, req.(*DesignQuoteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DesignService_CreateDesignP2P_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DesignP2PRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DesignServiceServer).CreateDesignP2P(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DesignService_CreateDesignP2P_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DesignServiceServer).CreateDesignP2P(ctx, req.(*DesignP2PRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DesignService_CreateDesignPMStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DesignPMStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DesignServiceServer).CreateDesignPMStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DesignService_CreateDesignPMStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DesignServiceServer).CreateDesignPMStatus(ctx, req.(*DesignPMStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DesignService_GetDesignNotificationFeed_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DesignNotificationFeedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DesignServiceServer).GetDesignNotificationFeed(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DesignService_GetDesignNotificationFeed_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DesignServiceServer).GetDesignNotificationFeed(ctx, req.(*DesignNotificationFeedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DesignService_GetDesignNotificationDetails_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DesignNotificationDetailsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DesignServiceServer).GetDesignNotificationDetails(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DesignService_GetDesignNotificationDetails_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DesignServiceServer).GetDesignNotificationDetails(ctx, req.(*DesignNotificationDetailsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DesignService_GetDesignNotificationCounts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DesignNotificationCountsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DesignServiceServer).GetDesignNotificationCounts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DesignService_GetDesignNotificationCounts_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DesignServiceServer).GetDesignNotificationCounts(ctx, req.(*DesignNotificationCountsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DesignService_GetDesignInbox_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DesignInboxRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DesignServiceServer).GetDesignInbox(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DesignService_GetDesignInbox_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DesignServiceServer).GetDesignInbox(ctx, req.(*DesignInboxRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DesignService_GetDesignInboxCounts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DesignInboxCountsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DesignServiceServer).GetDesignInboxCounts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DesignService_GetDesignInboxCounts_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DesignServiceServer).GetDesignInboxCounts(ctx, req.(*DesignInboxCountsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DesignService_MarkDesignNotificationRead_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MarkDesignNotificationReadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DesignServiceServer).MarkDesignNotificationRead(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DesignService_MarkDesignNotificationRead_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DesignServiceServer).MarkDesignNotificationRead(ctx, req.(*MarkDesignNotificationReadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DesignService_MarkAllDesignNotificationsRead_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MarkAllDesignNotificationsReadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DesignServiceServer).MarkAllDesignNotificationsRead(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DesignService_MarkAllDesignNotificationsRead_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DesignServiceServer).MarkAllDesignNotificationsRead(ctx, req.(*MarkAllDesignNotificationsReadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DesignService_CreateDesignInboxTicket_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateDesignInboxTicketRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DesignServiceServer).CreateDesignInboxTicket(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DesignService_CreateDesignInboxTicket_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DesignServiceServer).CreateDesignInboxTicket(ctx, req.(*CreateDesignInboxTicketRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DesignService_ServiceDesc is the grpc.ServiceDesc for DesignService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DesignService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "design.DesignService",
	HandlerType: (*DesignServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateDesignLeadPre10",
			Handler:    _DesignService_CreateDesignLeadPre10_Handler,
		},
		{
			MethodName: "CreateDesignLead1020",
			Handler:    _DesignService_CreateDesignLead1020_Handler,
		},
		{
			MethodName: "CreateDesignMilestone",
			Handler:    _DesignService_CreateDesignMilestone_Handler,
		},
		{
			MethodName: "CreateDesignPaymentRequest",
			Handler:    _DesignService_CreateDesignPaymentRequest_Handler,
		},
		{
			MethodName: "CreateDesignPaymentStatus",
			Handler:    _DesignService_CreateDesignPaymentStatus_Handler,
		},
		{
			MethodName: "CreateDesignDQCRequest",
			Handler:    _DesignService_CreateDesignDQCRequest_Handler,
		},
		{
			MethodName: "CreateDesignDQCStatus",
			Handler:    _DesignService_CreateDesignDQCStatus_Handler,
		},
		{
			MethodName: "CreateDesignMMTRequest",
			Handler:    _DesignService_CreateDesignMMTRequest_Handler,
		},
		{
			MethodName: "CreateDesignMMTAssign",
			Handler:    _DesignService_CreateDesignMMTAssign_Handler,
		},
		{
			MethodName: "CreateDesignMMTDocReady",
			Handler:    _DesignService_CreateDesignMMTDocReady_Handler,
		},
		{
			MethodName: "CreateDesignMeeting",
			Handler:    _DesignService_CreateDesignMeeting_Handler,
		},
		{
			MethodName: "CreateDesignAssignDesigner",
			Handler:    _DesignService_CreateDesignAssignDesigner_Handler,
		},
		{
			MethodName: "CreateDesignAssignPM",
			Handler:    _DesignService_CreateDesignAssignPM_Handler,
		},
		{
			MethodName: "CreateDesignQuote",
			Handler:    _DesignService_CreateDesignQuote_Handler,
		},
		{
			MethodName: "CreateDesignP2P",
			Handler:    _DesignService_CreateDesignP2P_Handler,
		},
		{
			MethodName: "CreateDesignPMStatus",
			Handler:    _DesignService_CreateDesignPMStatus_Handler,
		},
		{
			MethodName: "GetDesignNotificationFeed",
			Handler:    _DesignService_GetDesignNotificationFeed_Handler,
		},
		{
			MethodName: "GetDesignNotificationDetails",
			Handler:    _DesignService_GetDesignNotificationDetails_Handler,
		},
		{
			MethodName: "GetDesignNotificationCounts",
			Handler:    _DesignService_GetDesignNotificationCounts_Handler,
		},
		{
			MethodName: "GetDesignInbox",
			Handler:    _DesignService_GetDesignInbox_Handler,
		},
		{
			MethodName: "GetDesignInboxCounts",
			Handler:    _DesignService_GetDesignInboxCounts_Handler,
		},
		{
			MethodName: "MarkDesignNotificationRead",
			Handler:    _DesignService_MarkDesignNotificationRead_Handler,
		},
		{
			MethodName: "MarkAllDesignNotificationsRead",
			Handler:    _DesignService_MarkAllDesignNotificationsRead_Handler,
		},
		{
			MethodName: "CreateDesignInboxTicket",
			Handler:    _DesignService_CreateDesignInboxTicket_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "design.proto",
}
